jsm174/vpx-standalone-scripts

Pulp Fiction 3.1/pulp_fiction.vbs, Pulp Fiction 3.1/pulp_fiction.vbs.original, Pulp Fiction 3.1/pulp_fiction.vbs.patch
https://vpuniverse.com/files/file/14616-pulp-fiction/
=> Pulp Fiction 3.1

Flash (Williams 1979) bord/Flash (Williams 1979) bord.vbs, Flash (Williams 1979) bord/Flash (Williams 1979) bord.vbs.original, Flash (Williams 1979) bord/Flash (Williams 1979) bord.vbs.patch
https://vpuniverse.com/files/file/9230-flash-williams-1979/ (1.0)
Not to be confused with the JPSalas version that is at v4
=> Flash (Williams 1979) bord

AceOfSpeed/AceOfSpeed.vbs, AceOfSpeed/AceOfSpeed.vbs.original, AceOfSpeed/AceOfSpeed.vbs.patch
https://vpuniverse.com/files/file/6253-ace-of-speed/
Bug reported on wine vbscript at https://bugs.winehq.org/show_bug.cgi?id=55093
=> AceOfSpeed

Barracora (Williams 1981) w VR Room v2.1.2/Barracora (Williams 1981) w VR Room v2.1.2.vbs, Barracora (Williams 1981) w VR Room v2.1.2/Barracora (Williams 1981) w VR Room v2.1.2.vbs.original, Barracora (Williams 1981) w VR Room v2.1.2/Barracora (Williams 1981) w VR Room v2.1.2.vbs.patch
https://vpuniverse.com/files/file/12694-barracora-williams-1981-w-vr-room/
=> Barracora (Williams 1981) w VR Room v2.1.2

Seawitch (Stern 1980)/Seawitch (Stern 1980).vbs, Seawitch (Stern 1980)/Seawitch (Stern 1980).vbs.original, Seawitch (Stern 1980)/Seawitch (Stern 1980).vbs.patch
This is for the `bord` version
https://vpuniverse.com/files/file/6534-seawitch-stern-1980-bord/
However the digits are not rendered as already discussed in previous tickets
=> Seawitch (Stern 1980)

Robot (Zaccaria 1985) v1.2/Robot (Zaccaria 1985) v1.2.vbs, Robot (Zaccaria 1985) v1.2/Robot (Zaccaria 1985) v1.2.vbs.original, Robot (Zaccaria 1985) v1.2/Robot (Zaccaria 1985) v1.2.vbs.patch
contains the fix mentioned in #24
=> Robot (Zaccaria 1985) v1.2

Led Zeppelin Pinball 2.5/Led Zeppelin Pinball 2.5.vbs, Led Zeppelin Pinball 2.5/Led Zeppelin Pinball 2.5.vbs.original, Led Zeppelin Pinball 2.5/Led Zeppelin Pinball 2.5.vbs.patch
https://vpuniverse.com/files/file/5940-led-zeppelin-pinball/
=> Led Zeppelin Pinball 2.5

Elektra (Bally 1981) w VR Room v2.0.7/Elektra (Bally 1981) w VR Room v2.0.7.vbs, Elektra (Bally 1981) w VR Room v2.0.7/Elektra (Bally 1981) w VR Room v2.0.7.vbs.original, Elektra (Bally 1981) w VR Room v2.0.7/Elektra (Bally 1981) w VR Room v2.0.7.vbs.patch
This table runs veeery slow though, something to look into
=> Elektra (Bally 1981) w VR Room v2.0.7

Black Knight (Williams 1980)/Black Knight (Williams 1980).vbs, Black Knight (Williams 1980)/Black Knight (Williams 1980).vbs.original, Black Knight (Williams 1980)/Black Knight (Williams 1980).vbs.patch
There are two versions of this table, this is for https://vpuniverse.com/files/file/7629-black-knight-williams-1980/
The other version is https://www.vpforums.org/index.php?app=downloads&showfile=12055 and requires no patching
=> Black Knight (Williams 1980)

Bart VS the Space Mutants 1.1/Bart VS the Space Mutants 1.1.vbs, Bart VS the Space Mutants 1.1/Bart VS the Space Mutants 1.1.vbs.original, Bart VS the Space Mutants 1.1/Bart VS the Space Mutants 1.1.vbs.patch
Did a bit more than the usual fixes as this table is broken regarding credit / highscore loading
=> patch: Bart VS the Space Mutants 1.1

Mousin' Around! (Bally 1989) w VR Room v2.1/Mousin' Around! (Bally 1989) w VR Room v2.1.vbs, Mousin' Around! (Bally 1989) w VR Room v2.1/Mousin' Around! (Bally 1989) w VR Room v2.1.vbs.original, Mousin' Around! (Bally 1989) w VR Room v2.1/Mousin' Around! (Bally 1989) w VR Room v2.1.vbs.patch
same as #37 as that was a mod of this one
=> patch: Mousin' Around! (Bally 1989) w VR Room v2.1

Bram Stoker's Dracula (Williams 1993)/Bram Stokers Dracula (1993).vbs, Bram Stoker's Dracula (Williams 1993)/Bram Stokers Dracula (1993).vbs.original, Bram Stoker's Dracula (Williams 1993)/Bram Stokers Dracula (1993).vbs.patch
https://pinballnirvana.com/forums/resources/bram-stokers-dracula-williams-1993-vpx.6012/
=> patch: Bram Stoker's Dracula (Williams 1993)

O Brother Where Art Thou (Zoss 2021)1_6/O Brother Where Art Thou (Zoss 2021)1_6.vbs, O Brother Where Art Thou (Zoss 2021)1_6/O Brother Where Art Thou (Zoss 2021)1_6.vbs.original, O Brother Where Art Thou (Zoss 2021)1_6/O Brother Where Art Thou (Zoss 2021)1_6.vbs.patch
https://vpuniverse.com/files/file/7325-o-brother-where-art-thou/
=> patch: O Brother Where Art Thou (Zoss 2021)1_6

Cactus Jacks (Gottlieb 1991) w VR Room v2.0.2/Cactus Jacks (Gottlieb 1991) w VR Room v2.0.2.vbs, Cactus Jacks (Gottlieb 1991) w VR Room v2.0.2/Cactus Jacks (Gottlieb 1991) w VR Room v2.0.2.vbs.original, Cactus Jacks (Gottlieb 1991) w VR Room v2.0.2/Cactus Jacks (Gottlieb 1991) w VR Room v2.0.2.vbs.patch
`Cactus Jacks (Gottlieb 1991) w VR Room v2.0.2.vpx`
https://vpuniverse.com/files/file/9373-cactus-jacks-gottlieb-1991-w-vr-room/
waiting for #48
=> Cactus Jacks (Gottlieb 1991) w VR Room v2.0.2

Power Play (Bally 1977)/Power Play (Bally 1977).vbs, Power Play (Bally 1977)/Power Play (Bally 1977).vbs.original, Power Play (Bally 1977)/Power Play (Bally 1977).vbs.patch
https://vpuniverse.com/files/file/9794-bobby-orr-power-play-bally-1977/
=> Power Play (Bally 1977)

Comet (Williams 1985) w VR Room v2.3/Comet (Williams 1985) w VR Room v2.3.vbs, Comet (Williams 1985) w VR Room v2.3/Comet (Williams 1985) w VR Room v2.3.vbs.original, Comet (Williams 1985) w VR Room v2.3/Comet (Williams 1985) w VR Room v2.3.vbs.patch
https://vpuniverse.com/files/file/8673-comet-williams-1985-w-vr-room/
=> patch: Comet (Williams 1985) w VR Room v2.3

Cannes (Segasa 1976)V1.2/Cannes (Segasa 1976)V1.2.vbs, Cannes (Segasa 1976)V1.2/Cannes (Segasa 1976)V1.2.vbs.original, Cannes (Segasa 1976)V1.2/Cannes (Segasa 1976)V1.2.vbs.patch, Monaco (Segasa 1977)V1.3/Monaco (Segasa 1977)V1.3.vbs, Monaco (Segasa 1977)V1.3/Monaco (Segasa 1977)V1.3.vbs.original, Monaco (Segasa 1977)V1.3/Monaco (Segasa 1977)V1.3.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=17157
https://www.vpforums.org/index.php?app=downloads&showfile=17149
=> patch: Cannes (Segasa 1976)V1.2 / Monaco (Segasa 1977)V1.3

Seven Winner (Inder 1973) v4/Seven Winner (Inder 1973) v4.vbs, Seven Winner (Inder 1973) v4/Seven Winner (Inder 1973) v4.vbs.original, Seven Winner (Inder 1973) v4/Seven Winner (Inder 1973) v4.vbs.patch
=> patch: Seven Winner (Inder 1973) v4

Medusa (Bally 1981) w VR Room v2.0.1/Medusa (Bally 1981) w VR Room v2.0.1.vbs, Medusa (Bally 1981) w VR Room v2.0.1/Medusa (Bally 1981) w VR Room v2.0.1.vbs.original, Medusa (Bally 1981) w VR Room v2.0.1/Medusa (Bally 1981) w VR Room v2.0.1.vbs.patch
https://vpuniverse.com/files/file/15137-medusa-bally-1981-w-vr-room/
UnclePaulie
=> Medusa (Bally 1981) w VR Room v2.0.1

ABBAv2.0/ABBAv2.0.vbs, ABBAv2.0/ABBAv2.0.vbs.original, ABBAv2.0/ABBAv2.0.vbs.patch, Vortex (Taito do Brasil - 1981) v4/Vortex (Taito do Brasil - 1981) v4.vbs, Vortex (Taito do Brasil - 1981) v4/Vortex (Taito do Brasil - 1981) v4.vbs.original, Vortex (Taito do Brasil - 1981) v4/Vortex (Taito do Brasil - 1981) v4.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=13336
This disables the `NVram patch for Taito do Brasil tables by Pmax65`
Table works but keeps it's state over restarts, so if you come back after exiting you continue the previously running game.
Same patch is required for `ABBAv2.0.vpx` which is based on Vortex.
https://vpuniverse.com/files/file/5782-abba-v20/
=> patch: Vortex (Taito do Brasil - 1981) v4 / ABBAv2.0

Viking (Bally 1980)/Viking (Bally 1980).vbs, Viking (Bally 1980)/Viking (Bally 1980).vbs.original, Viking (Bally 1980)/Viking (Bally 1980).vbs.patch
https://vpuniverse.com/files/file/12163-viking-bally-1980/
=> patch: Viking (Bally 1980)

Batman Forever (Sega 1995) 1.3/Batman Forever (Sega 1995) 1.3.vbs, Batman Forever (Sega 1995) 1.3/Batman Forever (Sega 1995) 1.3.vbs.original, Batman Forever (Sega 1995) 1.3/Batman Forever (Sega 1995) 1.3.vbs.patch
https://vpuniverse.com/files/file/11601-batman-forever-drakkon-mod-11/
=> patch: Batman Forever (Sega 1995) 1.3

The Phantom Of The Opera (Data East 1990)/The Phantom Of The Opera (Data East 1990).vbs, The Phantom Of The Opera (Data East 1990)/The Phantom Of The Opera (Data East 1990).vbs.original, The Phantom Of The Opera (Data East 1990)/The Phantom Of The Opera (Data East 1990).vbs.patch
https://vpuniverse.com/files/file/5563-the-phantom-of-the-opera-data-east-1990/
same patch is needed for the bigus mod but not creating a patch for that
https://www.vpforums.org/index.php?app=downloads&showfile=14295
=> patch: The Phantom Of The Opera (Data East 1990)

Jive Time (Williams 1970) 2.0/Jive Time (Williams 1970) 2.0.vbs, Jive Time (Williams 1970) 2.0/Jive Time (Williams 1970) 2.0.vbs.original, Jive Time (Williams 1970) 2.0/Jive Time (Williams 1970) 2.0.vbs.patch
https://vpuniverse.com/files/file/8621-jive-time-williams-1970/
=> patch: Jive Time (Williams 1970) 2.0

SpaceRamp (SuperEd) v3.03b/SpaceRamp (SuperEd) v3.03b.vbs, SpaceRamp (SuperEd) v3.03b/SpaceRamp (SuperEd) v3.03b.vbs.original, SpaceRamp (SuperEd) v3.03b/SpaceRamp (SuperEd) v3.03b.vbs.patch
https://vpuniverse.com/files/file/15682-spaceramp-supered-original-v303b/
wip, see also #83
=> patch: SpaceRamp (SuperEd) v3.03b

Wheel of Fortune (Stern 2007) 1.0/Wheel of Fortune (Stern 2007) 1.0.vbs, Wheel of Fortune (Stern 2007) 1.0/Wheel of Fortune (Stern 2007) 1.0.vbs.original, Wheel of Fortune (Stern 2007) 1.0/Wheel of Fortune (Stern 2007) 1.0.vbs.patch
https://vpuniverse.com/files/file/5501-wheel-of-fortune-stern-2007/
=> patch: Wheel of Fortune (Stern 2007) 1.0

Flash Gordon (Bally 1981) 2.0.2/Flash Gordon (Bally 1981) 2.0.2.vbs, Flash Gordon (Bally 1981) 2.0.2/Flash Gordon (Bally 1981) 2.0.2.vbs.original, Flash Gordon (Bally 1981) 2.0.2/Flash Gordon (Bally 1981) 2.0.2.vbs.patch
https://vpuniverse.com/files/file/11584-flash-gordon-bally-1981/
=> patch: Flash Gordon (Bally 1981) 2.0.2

Zone Fury VPX 1.0.0/ZoneFuryVPX.vbs, Zone Fury VPX 1.0.0/ZoneFuryVPX.vbs.original, Zone Fury VPX 1.0.0/ZoneFuryVPX.vbs.patch
https://pinballnirvana.com/forums/threads/zone-fury-original-vpx.22522/
more of these annoying https://bugs.winehq.org/show_bug.cgi?id=54177
=> patch: Zone Fury 1.0.0

Surf'n Safari v1.3.4/Surf'n Safari v1.3.4.vbs, Surf'n Safari v1.3.4/Surf'n Safari v1.3.4.vbs.original, Surf'n Safari v1.3.4/Surf'n Safari v1.3.4.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=11868
=> patch: Surf'n Safari v1.3.4

Topaz (Inder 1979)/Topaz (Inder 1979).vbs, Topaz (Inder 1979)/Topaz (Inder 1979).vbs.original, Topaz (Inder 1979)/Topaz (Inder 1979).vbs.patch
=> patch: Topaz (Inder 1979)

Halloween 1978-1981 (Original 2022) 1.03/Halloween 1978-1981 (Original 2022) 1.03.vbs, Halloween 1978-1981 (Original 2022) 1.03/Halloween 1978-1981 (Original 2022) 1.03.vbs.original, Halloween 1978-1981 (Original 2022) 1.03/Halloween 1978-1981 (Original 2022) 1.03.vbs.patch
Halloween is this month so better get [this table](https://vpuniverse.com/files/file/11966-halloween-1978-1981-original-2022-vpx) working!  Thank you @jsm174 for your clear instructions for updating the DTArray and STArray bits.  There are what appears to be superflous changes in some lines like those around `StopSound"HTA 10"`, but those are inconsistent line endings in the original file.
=> patch: Halloween 1978-1981 (Original 2022) 1.03

Sonic The Hedgehog (Brendan Bailey 2005) VPX_(MOD)1.21/Sonic The Hedgehog (Brendan Bailey 2005) VPX_(MOD)1.21.vbs, Sonic The Hedgehog (Brendan Bailey 2005) VPX_(MOD)1.21/Sonic The Hedgehog (Brendan Bailey 2005) VPX_(MOD)1.21.vbs.original, Sonic The Hedgehog (Brendan Bailey 2005) VPX_(MOD)1.21/Sonic The Hedgehog (Brendan Bailey 2005) VPX_(MOD)1.21.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=17707
=> patch: Sonic The Hedgehog (Brendan Bailey 2005) VPX_(MOD)1.21

Ducktales (Orginal 2020)/DUCKTALES.vbs, Ducktales (Orginal 2020)/DUCKTALES.vbs.original, Ducktales (Orginal 2020)/DUCKTALES.vbs.patch
https://vpuniverse.com/files/file/8402-ducktales/
=> patch: Ducktales (Orginal 2020)

AceOfSpeed/.gitattributes
After this there is the option to do
```
$ git add --renormalize .
$ git status        # Show files that will be normalized
$ git commit -m "Introduce end-of-line normalization"
```
=> chore: set up .gitattributes

AceOfSpeed/AceOfSpeed.vbs, AceOfSpeed/AceOfSpeed.vbs.patch
fixes b2s not updating, see also #111
=> patch: Ace of Speed b2s update

Harlem Globetrotters (Bally 1979) v1.14/Harlem Globetrotters (Bally 1979) v1.14.vbs, Harlem Globetrotters (Bally 1979) v1.14/Harlem Globetrotters (Bally 1979) v1.14.vbs.original, Harlem Globetrotters (Bally 1979) v1.14/Harlem Globetrotters (Bally 1979) v1.14.vbs.patch
https://vpuniverse.com/files/file/13426-harlem-globetrotters-on-tour-bally-1979-mikcab_mod/?tab=comments
=> patch: Harlem Globetrotters (Bally 1979) v1.14

Atlantis (Bally 1989) w VR Room v2.0/Atlantis (Bally 1989) w VR Room v2.0.vbs, Atlantis (Bally 1989) w VR Room v2.0/Atlantis (Bally 1989) w VR Room v2.0.vbs.original, Atlantis (Bally 1989) w VR Room v2.0/Atlantis (Bally 1989) w VR Room v2.0.vbs.patch
https://vpuniverse.com/files/file/10348-atlantis-bally-1989-w-vr-room/
Also here the fulldmd does not show the dmd correctly (like mousin around)
https://vpuniverse.com/files/file/11248-atlantis-bally-1989-b2s-with-full-dmd/
=> patch: Atlantis (Bally 1989) w VR Room v2.0

Haunted House (Gottlieb 1982) VPW 2.0/Haunted House (Gottlieb 1982) VPW 2.0.vbs, Haunted House (Gottlieb 1982) VPW 2.0/Haunted House (Gottlieb 1982) VPW 2.0.vbs.original, Haunted House (Gottlieb 1982) VPW 2.0/Haunted House (Gottlieb 1982) VPW 2.0.vbs.patch
https://vpuniverse.com/files/file/16511-haunted-house-gottlieb-1982-vpw/
=> patch: Haunted House (Gottlieb 1982) VPW 2.0

Dracula (Stern 1979)2.1.1/Dracula (Stern 1979).vbs, Dracula (Stern 1979)2.1.1/Dracula (Stern 1979).vbs.original, Dracula (Stern 1979)2.1.1/Dracula (Stern 1979).vbs.patch
https://vpuniverse.com/files/file/11998-dracula-stern-1979/
=> patch: Dracula - Stern 1979 2.1.1

Drunken Santa (Original 2021)/DS.vbs, Drunken Santa (Original 2021)/DS.vbs.original, Drunken Santa (Original 2021)/DS.vbs.patch
https://vpuniverse.com/files/file/8400-drunken-santa/
=> patch: Drunken Santa (Original 2021)

Gemini (Gottlieb 1978)/Gemini (Gottlieb 1978).vbs, Gemini (Gottlieb 1978)/Gemini (Gottlieb 1978).vbs.original, Gemini (Gottlieb 1978)/Gemini (Gottlieb 1978).vbs.patch
https://vpuniverse.com/files/file/3632-gemini-gottlieb-1978-borgdog10vp10/
=> patch: Gemini (Gottlieb 1978)

Diablo Pinball v4.3/Diablo Pinball v4.3.vbs, Diablo Pinball v4.3/Diablo Pinball v4.3.vbs.original, Diablo Pinball v4.3/Diablo Pinball v4.3.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=12750
=> patch: Diablo Pinball v4.3

Mago de Oz - the pinball v4.3/Mago de Oz - the pinball v4.3.vbs, Mago de Oz - the pinball v4.3/Mago de Oz - the pinball v4.3.vbs.original, Mago de Oz - the pinball v4.3/Mago de Oz - the pinball v4.3.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=15598
=> patch: Mago de Oz - the pinball v4.3

Star Trek (Bally 1979) 2.1.1/Star Trek (Bally 1979) 2.1.1.vbs, Star Trek (Bally 1979) 2.1.1/Star Trek (Bally 1979) 2.1.1.vbs.original, Star Trek (Bally 1979) 2.1.1/Star Trek (Bally 1979) 2.1.1.vbs.patch
https://vpuniverse.com/files/file/8495-star-trek/
Typical DTArray patch performed by vpxtool
=> patch: Star Trek (Bally 1979) 2.1.1

Harley Davidson (Sega 1999) v1.12/Harley Davidson (Sega 1999) v1.12.vbs, Harley Davidson (Sega 1999) v1.12/Harley Davidson (Sega 1999) v1.12.vbs.original, Harley Davidson (Sega 1999) v1.12/Harley Davidson (Sega 1999) v1.12.vbs.patch
https://vpuniverse.com/files/file/10908-harley-davidson-sega-1999/?tab=details
=> patch: Harley Davidson (Sega 1999) v1.12

Hang Glider (Bally 1976) VPW v1.2/Hang Glider (Bally 1976) VPW v1.2.vbs, Hang Glider (Bally 1976) VPW v1.2/Hang Glider (Bally 1976) VPW v1.2.vbs.original, Hang Glider (Bally 1976) VPW v1.2/Hang Glider (Bally 1976) VPW v1.2.vbs.patch
https://vpuniverse.com/files/file/8056-hang-glider-bally-1976/
fixes #132
=> patch: Hang Glider (Bally 1976) VPW v1.2

Phantom Of The Opera (Data East 1990) v1.24/Phantom Of The Opera (Data East 1990) v1.24.vbs, Phantom Of The Opera (Data East 1990) v1.24/Phantom Of The Opera (Data East 1990) v1.24.vbs.original, Phantom Of The Opera (Data East 1990) v1.24/Phantom Of The Opera (Data East 1990) v1.24.vbs.patch
https://vpuniverse.com/files/file/17168-phantom-of-the-opera-data-east-1990
=> patch: Phantom Of The Opera (Data East 1990) v1.24

Super Star (Williams 1972) v4.3/Super Star (Williams 1972) v4.3.vbs, Super Star (Williams 1972) v4.3/Super Star (Williams 1972) v4.3.vbs.original, Super Star (Williams 1972) v4.3/Super Star (Williams 1972) v4.3.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=14461
=> patch: Super Star (Williams 1972) v4.3

Big Star (Williams 1972) v4.3/Big Star (Williams 1972) v4.3.vbs, Big Star (Williams 1972) v4.3/Big Star (Williams 1972) v4.3.vbs.original, Big Star (Williams 1972) v4.3/Big Star (Williams 1972) v4.3.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=14460#
Same patch as `Super Star`
=> patch: Big Star (Williams 1972) v4.3

281452208_SwordsofFury(Williams1988)1.0.1/Swords of Fury (Williams 1988).vbs, 281452208_SwordsofFury(Williams1988)1.0.1/Swords of Fury (Williams 1988).vbs.original, 281452208_SwordsofFury(Williams1988)1.0.1/Swords of Fury (Williams 1988).vbs.patch
https://vpuniverse.com/files/file/11517-swords-of-fury-williams-1988/
=> patch: 281452208_SwordsofFury(Williams1988)1.0.1

Attack and Revenge from Mars v4.3/Attack and Revenge from Mars v4.3.vbs, Attack and Revenge from Mars v4.3/Attack and Revenge from Mars v4.3.vbs.original, Attack and Revenge from Mars v4.3/Attack and Revenge from Mars v4.3.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=11604
see https://github.com/vpinball/vpinball/issues/1188
If you are using a rom folder inside the table folder the nvram files are not shared. So not using the offset will not mix up nvram between different Attack From Mars tables.
=> patch: Attack and Revenge from Mars v4.3

Pat Hand (Williams 1975)V1.3/Pat Hand (Williams 1975)V1.3.vbs, Pat Hand (Williams 1975)V1.3/Pat Hand (Williams 1975)V1.3.vbs.original, Pat Hand (Williams 1975)V1.3/Pat Hand (Williams 1975)V1.3.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=17100
=> patch: Pat Hand (Williams 1975)V1.3

Black & Red (Inder 1975) v4.3/Black & Red (Inder 1975) v4.3.vbs, Black & Red (Inder 1975) v4.3/Black & Red (Inder 1975) v4.3.vbs.original, Black & Red (Inder 1975) v4.3/Black & Red (Inder 1975) v4.3.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=16238#
=> patch: Black & Red (Inder 1975) v4.3

Space Shuttle (Williams 1984)2.0/Space Shuttle (Williams 1984).vbs, Space Shuttle (Williams 1984)2.0/Space Shuttle (Williams 1984).vbs.original, Space Shuttle (Williams 1984)2.0/Space Shuttle (Williams 1984).vbs.patch
https://vpuniverse.com/files/file/7492-space-shuttle-williams-1984/
=> patch: Space Shuttle (Williams 1984)2.0

1593887667_BountyHunter(Gottlieb1985)1.0/Bounty Hunter (Gottlieb 1985).vbs, 1593887667_BountyHunter(Gottlieb1985)1.0/Bounty Hunter (Gottlieb 1985).vbs.original, 1593887667_BountyHunter(Gottlieb1985)1.0/Bounty Hunter (Gottlieb 1985).vbs.patch
Bord's version available from https://vpuniverse.com/files/file/6250-bounty-hunter-gottlieb-1985/
Automatically corrected with vpxtool frontend
No scoring displayed on the table, but the table works.
=> patch: Bounty Hunter (Gottlieb 1985) 1.0.0

Pole Position (Sonic 1987)2.0/Pole Position (Sonic 1987)2.0.vbs, Pole Position (Sonic 1987)2.0/Pole Position (Sonic 1987)2.0.vbs.original, Pole Position (Sonic 1987)2.0/Pole Position (Sonic 1987)2.0.vbs.patch
https://vpuniverse.com/files/file/11572-pole-position-sonic-1987/
typical STArray issue patched with vpxtool
=> patch: Pole Position (Sonic 1987)2.0

South Park (Sega 1999) 1.3/South Park (Sega 1999) 1.3.vbs_dmd_hack
the usual hack to display the dmd
=> dmd_hack: South Park (Sega 1999) 1.3

Blood Machines 2.0/Blood Machines 2.0.vbs_dmd_hack
the usual hack to display the dmd in desktop mode
=> dmd_hack: Blood Machines 2.0

SpongeBob's Bikini Bottom Pinball VPW 2.1/SpongeBob's Bikini Bottom Pinball VPW 2.1.vbs.original, SpongeBob's Bikini Bottom Pinball VPW 2.1/SpongeBob's Bikini Bottom Pinball VPW 2.1.vbs_dmd_hack
I just followed the instructions from jsm174.
The table works without any hack, but you need this to display the dmd in desktop mode.
=> dmd_hack: SpongeBob's Bikini Bottom Pinball VPW 2.1.vbs

The Goonies Never Say Die Pinball (VPW 2021)v1.3/The Goonies Never Say Die Pinball (VPW 2021)v1.3.vbs_dmd_hack
code indications from jsm174, just uploading for convenience
=> dmd_hack: The Goonies Never Say Die Pinball (VPW 2021)v1.3

Hook (Data East 1992)_VPWmod_v1.0/Hook (Data East 1992)_VPWmod_v1.0.vbs.original, Hook (Data East 1992)_VPWmod_v1.0/Hook (Data East 1992)_VPWmod_v1.0.vbs_dmd_hack
Hook is working without any patches, but t display the dmd, you need to add the Sub ImplicitDMD_Init hack Hook's DMD ratio is 128x16 which is not very usual. I've put this ratio in the Sub ImplicitDMD_Init
=> dmd_hack: Hook (Data East 1992)_VPWmod_v1.0

BarbWire(Gottlieb1996)JoePicassoModv1.2/BarbWire(Gottlieb1996)JoePicassoModv1.2.vbs_dmd_hack
As discussed on discord, this could help people display a dmd in desktop mode, while maintaining a minimal clean code on the .vbs file.
=> dmd_hack: BarbWire(Gottlieb1996)JoePicassoModv1.2

Centaur (Bally 1981)/Centaur (Bally 1981).vbs.dmd, Centaur (Bally 1981)/Centaur (Bally 1981).vbs.dmd.patch
=> dmd_hack: Centaur (Bally 1981)

Space Shuttle (Williams 1984)2.0/Space Shuttle (Williams 1984).vbs.dmd, Space Shuttle (Williams 1984)2.0/Space Shuttle (Williams 1984).vbs.dmd.patch
as usual to display the dmd...
=> dmd_hack: Space Shuttle (Williams 1984)

Seawitch (Stern 1980)/Seawitch (Stern 1980).vbs.dmd, Seawitch (Stern 1980)/Seawitch (Stern 1980).vbs.dmd.patch
=> dmd_hack: Seawitch (Stern 1980)

Pink Panther (Gottlieb 1981)/Pink Panther (Gottlieb 1981).vbs.dmd, Pink Panther (Gottlieb 1981)/Pink Panther (Gottlieb 1981).vbs.dmd.patch, Pink Panther (Gottlieb 1981)/Pink Panther (Gottlieb 1981).vbs.original
the table runs without a modified .vbs file, but a patch is required to display the dmd
=> dmd_hack: Pink Panther (Gottlieb 1981)

Goin' Nuts (Gottlieb 1983)/Goin' Nuts (Gottlieb 1983).vbs.dmd, Goin' Nuts (Gottlieb 1983)/Goin' Nuts (Gottlieb 1983).vbs.dmd.patch, Goin' Nuts (Gottlieb 1983)/Goin' Nuts (Gottlieb 1983).vbs.original
this table doesn't need a modified .vbs to run, so I just uploaded the vps.dmd required to display the dmd.
=> dmd_hack: Goin' Nuts (Gottlieb 1983)

1593887667_BountyHunter(Gottlieb1985)1.0/Bounty Hunter (Gottlieb 1985).vbs.dmd, 1593887667_BountyHunter(Gottlieb1985)1.0/Bounty Hunter (Gottlieb 1985).vbs.dmd.patch
bord's table doesn't display the dmd by default
=> dmd_hack: Bounty Hunter (Gottlieb 1985)

303498555_Taxi(Williams1988)VPWv1.2.2.vpx/Taxi (Williams 1988) VPW v1.2.2.vbs, 303498555_Taxi(Williams1988)VPWv1.2.2.vpx/Taxi (Williams 1988) VPW v1.2.2.vbs.dmd, 303498555_Taxi(Williams1988)VPWv1.2.2.vpx/Taxi (Williams 1988) VPW v1.2.2.vbs.dmd.patch, 303498555_Taxi(Williams1988)VPWv1.2.2.vpx/Taxi (Williams 1988) VPW v1.2.2.vbs.original, 303498555_Taxi(Williams1988)VPWv1.2.2.vpx/Taxi (Williams 1988) VPW v1.2.2.vbs.patch
there's already a patch, but it's for version 1.2.5 which can not be found (unless I did not search correctly...) The current version is here:
https://vpuniverse.com/files/file/7074-taxi-williams-1988-vpw-mod/ and it's 1.2.2
Of course, the corrections come from the 1.2.5 previous work (all credits go to francisdb) I join the usual dmd_hack which makes this table much more pleasant.
=> patch: Taxi (Williams 1988) VPW v1.2.2

Star Trek LE (Stern 2013) v1.09/Star Trek LE (Stern 2013) v1.09.vbs.dmd, Star Trek LE (Stern 2013) v1.09/Star Trek LE (Stern 2013) v1.09.vbs.dmd.patch
this should follow francisdb's patch on the same table to display the dmd. https://github.com/jsm174/vpx-standalone-scripts/pull/169
=> dmd_hack: Star Trek LE (Stern 2013) v1.09

Scared Stiff (Bally 1996) v1.29/Scared Stiff (Bally 1996) v1.29.vbs.dmd, Scared Stiff (Bally 1996) v1.29/Scared Stiff (Bally 1996) v1.29.vbs.dmd.patch
Add the dmd (and serum colored dmd which also works) to the table.
=> dmd_hack: Scared Stiff (Bally 1996) v1.29

Star Trek LE (Stern 2013) v1.09/Star Trek LE (Stern 2013) v1.09.vbs, Star Trek LE (Stern 2013) v1.09/Star Trek LE (Stern 2013) v1.09.vbs.original, Star Trek LE (Stern 2013) v1.09/Star Trek LE (Stern 2013) v1.09.vbs.patch
https://vpuniverse.com/files/file/17313-star-trek-le-stern-2013/
see https://github.com/vpinball/vpinball/pull/1216
see https://bugs.winehq.org/show_bug.cgi?id=55969
=> patch: Star Trek LE (Stern 2013) v1.09

Victory (Gottlieb 1987) 2.0.2/Victory (Gottlieb 1987) 2.0.2.vbs, Victory (Gottlieb 1987) 2.0.2/Victory (Gottlieb 1987) 2.0.2.vbs.original, Victory (Gottlieb 1987) 2.0.2/Victory (Gottlieb 1987) 2.0.2.vbs.patch
https://vpuniverse.com/files/file/10390-victory-gottlieb-1987/
- Move constants higher up
- An issue with setting up the dip switch editor, see also https://github.com/vpinball/vpinball/issues/1210
=> patch: Victory (Gottlieb 1987) 2.0.2

Stardust (Williams 1971) v4/Stardust (Williams 1971) v4.vbs, Stardust (Williams 1971) v4/Stardust (Williams 1971) v4.vbs.original, Stardust (Williams 1971) v4/Stardust (Williams 1971) v4.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=14725
=> patch: Stardust (Williams 1971) v4

Cue Ball Wizard (Gottlieb 1992) Mikcab_Mod v1.2.4/Cue Ball Wizard (Gottlieb 1992) v1.2.4.vbs.dmd, Cue Ball Wizard (Gottlieb 1992) Mikcab_Mod v1.2.4/Cue Ball Wizard (Gottlieb 1992) v1.2.4.vbs.dmd.patch, Cue Ball Wizard (Gottlieb 1992) Mikcab_Mod v1.2.4/Cue Ball Wizard (Gottlieb 1992) v1.2.4.vbs.original
It's necessary for the dmd and also works if we use the very nice colored dmd (serum colorization). That's the recommended table by the author of the dmd colorization: https://vpuniverse.com/files/file/13580-cue-ball-wizard-gottlieb-1992-dmd-64-colors-serum-colorization/
=> dmd_hack: Cue Ball Wizard (Gottlieb 1992) Mikcab_Mod v1.2.4

Guns N Roses (Data East 1994) VPW v1.1/Guns N Roses (Data East 1994) VPW v1.1.vbs.dmdcolored, Guns N Roses (Data East 1994) VPW v1.1/Guns N Roses (Data East 1994) VPW v1.1.vbs.dmdcolored.patch, Guns N Roses (Data East 1994) VPW v1.1/Guns N Roses (Data East 1994) VPW v1.1.vbs.original
to use with https://vpuniverse.com/files/file/17131-guns-n-roses-data-east-1994-dmd-64-colors-serum-format/
=> dmdcolored_hack: Guns N Roses (Data East 1994) VPW v1.1

Tron Legacy (Stern 2011) VPW Mod v1.1/Tron Legacy (Stern 2011) VPW Mod v1.1.vbs.dmdcolored, Tron Legacy (Stern 2011) VPW Mod v1.1/Tron Legacy (Stern 2011) VPW Mod v1.1.vbs.dmdcolored.patch, Tron Legacy (Stern 2011) VPW Mod v1.1/Tron Legacy (Stern 2011) VPW Mod v1.1.vbs.original
To use the beautiful serum colorization, you need this hack, otherwise, the dmd won't display. https://vpuniverse.com/files/file/14216-tron-legacy-stern-2011-dmd-64-colors-serum-format-v22-final/ With non colored dmd, the dmd displays without any patch vbs file.
=> dmdcolored_hack: Tron Legacy (Stern 2011) VPW Mod v1.1

Champion Pub (Williams 1998) v1.43/Champion Pub (Williams 1998) v1.43.vbs.dmdcolored, Champion Pub (Williams 1998) v1.43/Champion Pub (Williams 1998) v1.43.vbs.dmdcolored.patch, Champion Pub (Williams 1998) v1.43/Champion Pub (Williams 1998) v1.43.vbs.original
to use the serum colored dmd, you need this patch, otherwise no dmd will display. https://vpuniverse.com/files/file/8573-champion-pub-64-colors/ The dmd appears without any modification on the table when not using a colored dmd.
=> dmdcolored_hack: Champion Pub (Williams 1998) v1.43

Diner (Williams 1990) VPW Mod 1.0.2/Diner (Williams 1990) VPW Mod 1.0.2.vbs.dmdcolored, Diner (Williams 1990) VPW Mod 1.0.2/Diner (Williams 1990) VPW Mod 1.0.2.vbs.dmdcolored.patch
This is the modified .vbs to allow the display of the serum colorized dmd (https://vpuniverse.com/files/file/15442-diner-williams-1990-dmd-64-colors-serum-format/) Serum is supported by vpx standalone, but without easy to use scripts, few people will use those colored dmd.
=> dmdcolored_hack: diner

HeatWave(Williams1964)1.0/Heat Wave (Williams 1964).vbs, HeatWave(Williams1964)1.0/Heat Wave (Williams 1964).vbs.original, HeatWave(Williams1964)1.0/Heat Wave (Williams 1964).vbs.patch
https://vpuniverse.com/files/file/7324-heat-wave-williams-1964/
typical patch created with vpxtool
=> patch: HeatWave(Williams1964)1.0

Avatar (Stern 2012) v1.12.vbs.dmd, Avatar (Stern 2012) v1.12.vbs.dmd.patch, Avatar (Stern 2012) v1.12.vbs.original
Table is from
https://vpuniverse.com/files/file/6408-avatar-stern-2012oqqsanmod/
=> dmd: Avatar (Stern 2012) v1.12

Robocop (Data East 1989)_drakkon(mod_1.2)/Robocop (Data East 1989)_drakkon(mod_1.2).vbs, Robocop (Data East 1989)_drakkon(mod_1.2)/Robocop (Data East 1989)_drakkon(mod_1.2).vbs.original, Robocop (Data East 1989)_drakkon(mod_1.2)/Robocop (Data East 1989)_drakkon(mod_1.2).vbs.patch
https://vpuniverse.com/files/file/11752-robocop-data-east-1989-drakkon-mod-12/
Typical DT/STArray fix with vpxtool
=> patch: Robocop (Data East 1989)_drakkon(mod_1.2)

Putin Vodka Mania (Original 2022)/PVM.vbs, Putin Vodka Mania (Original 2022)/PVM.vbs.original, Putin Vodka Mania (Original 2022)/PVM.vbs.patch
https://vpuniverse.com/files/file/12508-putin-vodka-mania/
=> patch: Putin Vodka Mania (Original 2022)

Strip-Joker-Poker-(Gottlieb-1978)-1.5/Strip Joker Poker (Gottlieb 1978) 1.5.vbs, Strip-Joker-Poker-(Gottlieb-1978)-1.5/Strip Joker Poker (Gottlieb 1978) 1.5.vbs.original, Strip-Joker-Poker-(Gottlieb-1978)-1.5/Strip Joker Poker (Gottlieb 1978) 1.5.vbs.patch
https://vpuniverse.com/files/file/9696-strip-joker-poker-gottlieb-1978-special-edition-complete-package/
Patched with vpxtool
=> patch: Strip-Joker-Poker-(Gottlieb-1978)-1.5

Laser Cue (Williams 1984) w VR Room 2.0.0/Laser Cue (Williams 1984) w VR Room 2.0.0.vbs, Laser Cue (Williams 1984) w VR Room 2.0.0/Laser Cue (Williams 1984) w VR Room 2.0.0.vbs.original, Laser Cue (Williams 1984) w VR Room 2.0.0/Laser Cue (Williams 1984) w VR Room 2.0.0.vbs.patch
https://vpuniverse.com/files/file/12912-laser-cue-williams-1984-w-vr-room
patched with vpxtool
=> patch: Laser Cue (Williams 1984) w VR Room 2.0.0

Honey (Williams 1971)V1.2/Honey (Williams 1971)V1.2.vbs, Honey (Williams 1971)V1.2/Honey (Williams 1971)V1.2.vbs.original, Honey (Williams 1971)V1.2/Honey (Williams 1971)V1.2.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=16915
=> patch: Honey (Williams 1971)V1.2

Magic City (Williams 1967)1.0a/Magic City (Williams 1967).vbs, Magic City (Williams 1967)1.0a/Magic City (Williams 1967).vbs.original, Magic City (Williams 1967)1.0a/Magic City (Williams 1967).vbs.patch
https://vpuniverse.com/files/file/13293-magic-city-williams-1967-mod/
typical patch made with vpxtool
=> patch: Magic City (Williams 1967)1.0a

Playboy(Stern2002)v1.1/Playboy (Stern 2002) v1.1.vbs, Playboy(Stern2002)v1.1/Playboy (Stern 2002) v1.1.vbs.original, Playboy(Stern2002)v1.1/Playboy (Stern 2002) v1.1.vbs.patch
https://vpuniverse.com/files/file/8359-playboy-stern-2002/
another case of https://github.com/vpinball/vpinball/issues/1210
=> patch: Playboy(Stern2002)v1.1

Junkyard Cats_1.07/Junkyard Cats_1.07.vbs, Junkyard Cats_1.07/Junkyard Cats_1.07.vbs.original, Junkyard Cats_1.07/Junkyard Cats_1.07.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=14106
existing wine issue: https://bugs.winehq.org/show_bug.cgi?id=55037
=> patch: Junkyard Cats_1.07

The Grinch - Original 2022/The Grinch (Original 2022) pinballfan2018.vbs, The Grinch - Original 2022/The Grinch (Original 2022) pinballfan2018.vbs.original, The Grinch - Original 2022/The Grinch (Original 2022) pinballfan2018.vbs.patch
https://vpuniverse.com/files/file/17453-the-grinch-original-2023/
=> patch: The Grinch - Original 2022

TheATeam_2.0.4/TheATeam.vbs, TheATeam_2.0.4/TheATeam.vbs.original, TheATeam_2.0.4/TheATeam.vbs.patch
https://vpuniverse.com/files/file/17525-the-a-team-original-pinball/
=> patch: TheATeam_2.0.4

speakeasy4/speakeasy4.vbs, speakeasy4/speakeasy4.vbs.original, speakeasy4/speakeasy4.vbs.patch
https://vpuniverse.com/files/file/8676-speakeasy-4-player-bally-1982/
=> patch: speakeasy4

cybernaut Bally/Cybernaut darkmod.vbs, cybernaut Bally/Cybernaut darkmod.vbs.original, cybernaut Bally/Cybernaut darkmod.vbs.patch, cybernaut Bally/Cybernaut.vbs, cybernaut Bally/Cybernaut.vbs.original, cybernaut Bally/Cybernaut.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=14322
variable declarations moved before use
=> patch: cybernaut Bally

A Charlie Brown Christmas feat. Vince Guaraldi (iDigStuff 2023) 1.0/A Charlie Brown Christmas feat. Vince Guaraldi (iDigStuff 2023).vbs, A Charlie Brown Christmas feat. Vince Guaraldi (iDigStuff 2023) 1.0/A Charlie Brown Christmas feat. Vince Guaraldi (iDigStuff 2023).vbs.original, A Charlie Brown Christmas feat. Vince Guaraldi (iDigStuff 2023) 1.0/A Charlie Brown Christmas feat. Vince Guaraldi (iDigStuff 2023).vbs.patch
https://vpuniverse.com/files/file/17613-a-charlie-brown-christmas-feat-the-vince-guaraldi-trio-idigstuff-2023-w-vr-room/
=> patch: A Charlie Brown Christmas

Fireball Classic (Bally 1984)1.2/Fireball Classic (Bally 1984)1.2.vbs, Fireball Classic (Bally 1984)1.2/Fireball Classic (Bally 1984)1.2.vbs.original, Fireball Classic (Bally 1984)1.2/Fireball Classic (Bally 1984)1.2.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=17312#
just moved some stuff around
=> patch: Fireball Classic (Bally 1984)1.2

Skylab (Williams 1974)V1.0/Skylab (Williams 1974)V1.0.vbs, Skylab (Williams 1974)V1.0/Skylab (Williams 1974)V1.0.vbs.original, Skylab (Williams 1974)V1.0/Skylab (Williams 1974)V1.0.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=18055
=> patch: Skylab (Williams 1974)V1.0

Sorcerer (Williams 1985) w VR Room v3.0/Sorcerer (Williams 1985) w VR Room v3.0.vbs, Sorcerer (Williams 1985) w VR Room v3.0/Sorcerer (Williams 1985) w VR Room v3.0.vbs.original, Sorcerer (Williams 1985) w VR Room v3.0/Sorcerer (Williams 1985) w VR Room v3.0.vbs.patch
https://vpuniverse.com/files/file/8504-sorcerer-williams-1985-w-vr-room/
- Standard DT/STArray patches with vpxtool
- CoRTracker fix
=> patch: Sorcerer (Williams 1985) w VR Room v3.0

AlienPoker(Williams1980)1.0/Alien Poker (Williams 1980).vbs, AlienPoker(Williams1980)1.0/Alien Poker (Williams 1980).vbs.original, AlienPoker(Williams1980)1.0/Alien Poker (Williams 1980).vbs.patch
https://vpuniverse.com/files/file/7796-alien-poker-williams-1980/
Standard DTArray patch made with vpxtool
=> patch: AlienPoker(Williams1980)1.0

Big Deal (Williams 1977)V2.0/Big Deal (Williams 1977)V2.0.vbs, Big Deal (Williams 1977)V2.0/Big Deal (Williams 1977)V2.0.vbs.original, Big Deal (Williams 1977)V2.0/Big Deal (Williams 1977)V2.0.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=16973
=> patch: Big Deal (Williams 1977)V2.0

Aztec (Williams 1976) 1.3 Mod Citedor JPJ-ARNGRIM-CED Team PP/Aztec (Williams 1976) 1.3 Mod Citedor JPJ-ARNGRIM-CED Team PP.vbs, Aztec (Williams 1976) 1.3 Mod Citedor JPJ-ARNGRIM-CED Team PP/Aztec (Williams 1976) 1.3 Mod Citedor JPJ-ARNGRIM-CED Team PP.vbs.original, Aztec (Williams 1976) 1.3 Mod Citedor JPJ-ARNGRIM-CED Team PP/Aztec (Williams 1976) 1.3 Mod Citedor JPJ-ARNGRIM-CED Team PP.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=15768
Had to first make sure the line endings were correct. A lot of lines are ended with only `CR` instead of `CRLF`
Otherwise a `const` being declared after use issue.
=> patch: Aztec (Williams 1976) 1.3 Mod Citedor JPJ-ARNGRIM-CED Team PP

Big Deal (Williams 1977)V2.1/Big Deal (Williams 1977)V2.1.vbs, Big Deal (Williams 1977)V2.1/Big Deal (Williams 1977)V2.1.vbs.original, Big Deal (Williams 1977)V2.1/Big Deal (Williams 1977)V2.1.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=16973
=> patch: Big Deal (Williams 1977)V2.1

Pat Hand (Williams 1975)V1.4/Pat Hand (Williams 1975)V1.4.vbs, Pat Hand (Williams 1975)V1.4/Pat Hand (Williams 1975)V1.4.vbs.original, Pat Hand (Williams 1975)V1.4/Pat Hand (Williams 1975)V1.4.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=17100
=> patch: Pat Hand (Williams 1975)V1.4

Skylab (Williams 1974)V1.3/Skylab (Williams 1974)V1.3.vbs, Skylab (Williams 1974)V1.3/Skylab (Williams 1974)V1.3.vbs.original, Skylab (Williams 1974)V1.3/Skylab (Williams 1974)V1.3.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=18055
=> patch: Skylab (Williams 1974)V1.3.vbs

High_Speed_(Williams 1986) v0.107a (MOD 3.0)/High_Speed_(Williams 1986) v0.107a (MOD 3.0).vbs, High_Speed_(Williams 1986) v0.107a (MOD 3.0)/High_Speed_(Williams 1986) v0.107a (MOD 3.0).vbs.original, High_Speed_(Williams 1986) v0.107a (MOD 3.0)/High_Speed_(Williams 1986) v0.107a (MOD 3.0).vbs.patch
https://vpuniverse.com/files/file/10373-high-speed-mod/
=> patch: High_Speed_(Williams 1986) v0.107a (MOD 3.0)

AC-DC LUCI Premium VR (Stern 2013) v1.1/AC-DC LUCI Premium VR (Stern 2013) v1.1.vbs.dmdcolored, AC-DC LUCI Premium VR (Stern 2013) v1.1/AC-DC LUCI Premium VR (Stern 2013) v1.1.vbs.dmdcolored.patch
A new serum colorisation has appeared: https://vpuniverse.com/files/file/17697-acdc-64-colors/
If you simply put the crz fle in altcolor, the dmd won't display anymore: you need these modifications
Closes #207 with eol corrections
=> dmdcolored_hack: AC-DC LUCI Premium VR (Stern 2013) v1.1

Bad Cats (Williams 1989) VPW 3.0/Bad Cats (Williams 1989) VPW 3.0.vbs.dmdcolored, Bad Cats (Williams 1989) VPW 3.0/Bad Cats (Williams 1989) VPW 3.0.vbs.dmdcolored.patch, Bad Cats (Williams 1989) VPW 3.0/Bad Cats (Williams 1989) VPW 3.0.vbs.original
This follows the nice serum colorisation from https://vpuniverse.com/files/file/18040-bad-cats-williams-1989-dmd-64-colors-serum-format/
I now try to use a github client to avoid the cr lf problems.
=> dmdcolored_hack: Bad Cats (Williams 1989) VPW 3.0

AC-DC ninuzzu 1.0 1.5/AC-DC Pro Vault-1.0.vbs, AC-DC ninuzzu 1.0 1.5/AC-DC Pro Vault-1.0.vbs.original, AC-DC ninuzzu 1.0 1.5/AC-DC Pro Vault-1.0.vbs.patch, AC-DC ninuzzu 1.0 1.5/AC-DC Pro-1.0.vbs, AC-DC ninuzzu 1.0 1.5/AC-DC Pro-1.0.vbs.original, AC-DC ninuzzu 1.0 1.5/AC-DC Pro-1.0.vbs.patch, AC-DC ninuzzu 1.0 1.5/AC-DC_Back In Black LE-1.5.vbs, AC-DC ninuzzu 1.0 1.5/AC-DC_Back In Black LE-1.5.vbs.original, AC-DC ninuzzu 1.0 1.5/AC-DC_Back In Black LE-1.5.vbs.patch, AC-DC ninuzzu 1.0 1.5/AC-DC_Let There Be Rock LE-1.5.vbs, AC-DC ninuzzu 1.0 1.5/AC-DC_Let There Be Rock LE-1.5.vbs.original, AC-DC ninuzzu 1.0 1.5/AC-DC_Let There Be Rock LE-1.5.vbs.patch, AC-DC ninuzzu 1.0 1.5/AC-DC_Luci-1.5.vbs, AC-DC ninuzzu 1.0 1.5/AC-DC_Luci-1.5.vbs.original, AC-DC ninuzzu 1.0 1.5/AC-DC_Luci-1.5.vbs.patch, AC-DC ninuzzu 1.0 1.5/AC-DC_Premium-1.5.vbs, AC-DC ninuzzu 1.0 1.5/AC-DC_Premium-1.5.vbs.original, AC-DC ninuzzu 1.0 1.5/AC-DC_Premium-1.5.vbs.patch
https://vpuniverse.com/files/file/5489-acdc/
=> patch: AC/DC ninuzzu 1.0 1.5

Lawman (Gottlieb 1971) 1.1/Lawman (Gottlieb 1971) 1.1.vbs, Lawman (Gottlieb 1971) 1.1/Lawman (Gottlieb 1971) 1.1.vbs.original, Lawman (Gottlieb 1971) 1.1/Lawman (Gottlieb 1971) 1.1.vbs.patch
https://vpuniverse.com/files/file/17788-lawman-gottlieb-1971-soundmod-4k/
Does some filesystem scan for music which does not work on standalone
Still interesting to keep as it should improve visuals and the [original Lawman](https://vpuniverse.com/files/file/8298-lawman-gottlieb-1971/) table [crashes standalone on startup](https://github.com/vpinball/vpinball/issues/1301)
=> patch: Lawman (Gottlieb 1971) 1.1

Defender (Williams 1982) VPW v1.2.1/Defender (Williams 1982) VPW v1.2.1.vbs, Defender (Williams 1982) VPW v1.2.1/Defender (Williams 1982) VPW v1.2.1.vbs.original, Defender (Williams 1982) VPW v1.2.1/Defender (Williams 1982) VPW v1.2.1.vbs.patch
https://vpuniverse.com/files/file/9456-defender-williams-1982-vpw/
=> patch: Defender (Williams 1982) VPW v1.2.1

Aladdin's Castle (Bally 1976) - DOZER - MJR_1.01/Aladdin's Castle (Bally 1976) - DOZER - MJR_1.01.vbs, Aladdin's Castle (Bally 1976) - DOZER - MJR_1.01/Aladdin's Castle (Bally 1976) - DOZER - MJR_1.01.vbs.original, Aladdin's Castle (Bally 1976) - DOZER - MJR_1.01/Aladdin's Castle (Bally 1976) - DOZER - MJR_1.01.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=13502
=> patch: Aladdin's Castle (Bally 1976) - DOZER - MJR_1.01

Bumper (Bill Port - 1977) v4/Bumper (Bill Port - 1977) v4.vbs, Bumper (Bill Port - 1977) v4/Bumper (Bill Port - 1977) v4.vbs.original, Bumper (Bill Port - 1977) v4/Bumper (Bill Port - 1977) v4.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=14184
=> patch: Bumper (Bill Port - 1977) v4

Death Proof Balutito V2/Death Proof Balutito V2.vbs, Death Proof Balutito V2/Death Proof Balutito V2.vbs.original, Death Proof Balutito V2/Death Proof Balutito V2.vbs.patch
https://vpuniverse.com/files/file/8050-death-proof-by-balutito/
Rom renamed as there is no VPMAlias.txt on standalone
=> patch: Death Proof Balutito V2

Fireball XL5/Fireball XL5.vbs, Fireball XL5/Fireball XL5.vbs.original, Fireball XL5/Fireball XL5.vbs.patch
https://vpuniverse.com/files/file/18224-fireballxl5/
This is for version `1.0.1`
=> patch: Fireball XL5

Beavis and Butt-head_Pinballed/Beavis and Butt-head_Pinballed.vbs, Beavis and Butt-head_Pinballed/Beavis and Butt-head_Pinballed.vbs.original, Beavis and Butt-head_Pinballed/Beavis and Butt-head_Pinballed.vbs.patch
https://vpuniverse.com/files/file/18299-beavis-and-butt-head-pinballed-bally-1993/
Reported to table author here:
https://vpuniverse.com/forums/topic/9903-new-vp10-alert-beavis-and-butt-head-pinballed-bally-1993/?do=findComment&comment=78352
=> patch: Beavis and Butt-head_Pinballed

Joker Poker EM (Gottlieb 1978) 1.6/Joker Poker EM (Gottlieb 1978) 1.6.vbs, Joker Poker EM (Gottlieb 1978) 1.6/Joker Poker EM (Gottlieb 1978) 1.6.vbs.original, Joker Poker EM (Gottlieb 1978) 1.6/Joker Poker EM (Gottlieb 1978) 1.6.vbs.patch
https://vpuniverse.com/files/file/14071-joker-poker-em-gottlieb-1978-smokey-blues-edition/
=> patch: Joker Poker EM (Gottlieb 1978) 1.6

Heavy Metal Meltdown (Bally 1987)/Heavy Metal Meltdown (Bally 1987).vbs, Heavy Metal Meltdown (Bally 1987)/Heavy Metal Meltdown (Bally 1987).vbs.original, Heavy Metal Meltdown (Bally 1987)/Heavy Metal Meltdown (Bally 1987).vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=11721
Just to make sure the backglass shows up
=> patch: Heavy Metal Meltdown (Bally 1987)

Safe Cracker (Bally 1996) v1.0/Safe Cracker (Bally 1996) v1.0.vbs, Safe Cracker (Bally 1996) v1.0/Safe Cracker (Bally 1996) v1.0.vbs.original, Safe Cracker (Bally 1996) v1.0/Safe Cracker (Bally 1996) v1.0.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=13536
https://vpuniverse.com/files/file/5162-safe-cracker-18-s11/
PinMAME has a default [alias](https://github.com/vpinball/pinmame/blob/699fabce6fb0f96ea0d8d31fa44ae3b92f45cc08/release/VPMAlias.txt#L4) `sc_18,sc_18s11`
But since standalone does not support aliasing `sc_18` is not found. Even if there is a file with that name. Because `sc_18` is [not part of the supported games](https://github.com/vpinball/pinmame/blob/699fabce6fb0f96ea0d8d31fa44ae3b92f45cc08/release/gamelist.txt#L1920-L1929).
=> patch: Safe Cracker (Bally 1996) v1.0

StarWars BountyHunter 3.02/StarWars BountyHunter 3.02.vbs, StarWars BountyHunter 3.02/StarWars BountyHunter 3.02.vbs.original, StarWars BountyHunter 3.02/StarWars BountyHunter 3.02.vbs.patch
https://vpuniverse.com/files/file/6450-starwars-bountyhunter/
=> patch: StarWars BountyHunter 3.02

World Poker Tour (Stern 2006)_Bigus(MOD)1.0/World Poker Tour (Stern 2006)_Bigus(MOD)1.0.vbs, World Poker Tour (Stern 2006)_Bigus(MOD)1.0/World Poker Tour (Stern 2006)_Bigus(MOD)1.0.vbs.original, World Poker Tour (Stern 2006)_Bigus(MOD)1.0/World Poker Tour (Stern 2006)_Bigus(MOD)1.0.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=16725
As indicated in https://github.com/vpinball/pinmame/issues/196 WPT also need a similar patch to #251
=> patch(pinmame-pwm): World Poker Tour (Stern 2006)_Bigus(MOD)1.0

Wheel of Fortune (Stern 2007) 1.0/Wheel of Fortune (Stern 2007) 1.0.vbs, Wheel of Fortune (Stern 2007) 1.0/Wheel of Fortune (Stern 2007) 1.0.vbs.patch
closes #247
https://vpuniverse.com/files/file/5501-wheel-of-fortune-stern-2007/
Some extra patches because newer pinmame versions with pwm report more lights
https://github.com/vpinball/pinmame/issues/196
I do however also have problems with the flippers on this table, sometimes a flipper is stuck in the up position. But don't think this has anything to do with the 2 lines modified here.
=> patch(pinmame-pwm): Wheel of Fortune (Stern 2007) 1.0

Party Animal (Bally 1987)/Party Animal (Bally 1987).vbs, Party Animal (Bally 1987)/Party Animal (Bally 1987).vbs.original, Party Animal (Bally 1987)/Party Animal (Bally 1987).vbs.patch
https://vpuniverse.com/files/file/5962-party-animal-bally-1987/
also needs pre-initialized nvram
https://www.vpforums.org/index.php?app=downloads&showfile=1362
Was a tricky one to find the fix for. Following destructor assertion was failing.
```cpp
Primitive::~Primitive()
{
WaitForMeshDecompression(); //!! needed nowadays due to multithreaded mesh decompression
assert(m_rd == nullptr); // RenderRelease must be explicitely called before deleting this object
}
```
https://github.com/vpinball/vpinball/blob/e7ea030c7da58b8edb93c5b417c7726c42d56eff/src/parts/primitive.cpp#L220-L224
Wonder if this double `InitPolarity` is on purpose or not.
@jsm174 not sure if anything should be done in the vpinball code to fix this case as on windows this does not crash.
=> patch: Party Animal (Bally 1987)

Grand Slam (Bally 1983) 2.3/Grand Slam (Bally 1983) 2.3.vbs, Grand Slam (Bally 1983) 2.3/Grand Slam (Bally 1983) 2.3.vbs.original, Grand Slam (Bally 1983) 2.3/Grand Slam (Bally 1983) 2.3.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=15115
=> patch: Grand Slam (Bally 1983) 2.3

Futurama (Original 2024)/Futurama (Original 2024) v1.1.vbs.dmd, Futurama (Original 2024)/Futurama (Original 2024) v1.1.vbs.dmd.patch, Futurama (Original 2024)/Futurama (Original 2024) v1.1.vbs.original
Because it's still more beautiful when integrated in the table
=> dmd_hack: Futurama (Original 2024)

Thunderbirds original 2022 v1.0.2/Thunderbirds original 2022 v1.0.2.vbs, Thunderbirds original 2022 v1.0.2/Thunderbirds original 2022 v1.0.2.vbs.original, Thunderbirds original 2022 v1.0.2/Thunderbirds original 2022 v1.0.2.vbs.patch
https://vpuniverse.com/files/file/10465-thunderbirds-original-2022/
These are the changes in flex dmd file name casing I found. Hope I found all.
=> patch: Thunderbirds original 2022 v1.0.2

Rally (Taito do Brasil - 1980) v4/Rally (Taito do Brasil - 1980) v4.vbs, Rally (Taito do Brasil - 1980) v4/Rally (Taito do Brasil - 1980) v4.vbs.original, Rally (Taito do Brasil - 1980) v4/Rally (Taito do Brasil - 1980) v4.vbs.patch
Removed the nvram patch loading. It was fetching the path from the registry.
[https://www.vpforums.org/index.php?app=downloads&showfile=13141](https://www.vpforums.org/index.php?app=downloads&showfile=13141)
=> Patch: Rally Taito V4

TRON Classic (Original 2022) v2.1/TRON Classic (Original 2022) v2.1.vbs, TRON Classic (Original 2022) v2.1/TRON Classic (Original 2022) v2.1.vbs.original, TRON Classic (Original 2022) v2.1/TRON Classic (Original 2022) v2.1.vbs.patch
Disable `NVOffset` from `core.vbs` as it tries to mingle with the registry.
https://www.vpforums.org/index.php?app=downloads&showfile=13554
=> patch: TRON Classic (Original 2022) v2.1

DarkPrincess1.3.1/DarkPrincess1.3.1.vbs, DarkPrincess1.3.1/DarkPrincess1.3.1.vbs.original, DarkPrincess1.3.1/DarkPrincess1.3.1.vbs.patch
https://vpuniverse.com/files/file/8119-darkprincess-original-2020-v13-update-sound-files
I put the music files next to the table in `./music`
=> patch: DarkPrincess1.3.1

Space Jam (Sega 1996) 1.4 JPJ - Edizzle - TeamPP - JLou/Space Jam (Sega 1996) 1.4 JPJ - Edizzle - TeamPP - JLou.vbs, Space Jam (Sega 1996) 1.4 JPJ - Edizzle - TeamPP - JLou/Space Jam (Sega 1996) 1.4 JPJ - Edizzle - TeamPP - JLou.vbs.original, Space Jam (Sega 1996) 1.4 JPJ - Edizzle - TeamPP - JLou/Space Jam (Sega 1996) 1.4 JPJ - Edizzle - TeamPP - JLou.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=15766
closes #201
=> patch: Space Jam (Sega 1996) 1.4 JPJ - Edizzle - TeamPP - JLou

Indiana Jones (Stern 2008)-Hanibal-2.6/Indiana Jones (Stern 2008)-Hanibal-2.6.vbs, Indiana Jones (Stern 2008)-Hanibal-2.6/Indiana Jones (Stern 2008)-Hanibal-2.6.vbs.original, Indiana Jones (Stern 2008)-Hanibal-2.6/Indiana Jones (Stern 2008)-Hanibal-2.6.vbs.patch
https://vpuniverse.com/files/file/4180-indiana-jones-stern2008-hanibals-4k-edition/
=> patch: Indiana Jones (Stern 2008)-Hanibal-2.6

SouthParkPinballv1.2/SPP.vbs, SouthParkPinballv1.2/SPP.vbs.original, SouthParkPinballv1.2/SPP.vbs.patch
https://vpuniverse.com/files/file/8395-south-park-pinball/
=> patch: SouthParkPinballv1.2

Titan (Taito do Brasil - 1981) v4/Titan (Taito do Brasil - 1981) v4.patch, Titan (Taito do Brasil - 1981) v4/Titan (Taito do Brasil - 1981) v4.vbs, Titan (Taito do Brasil - 1981) v4/Titan (Taito do Brasil - 1981) v4.vbs.original
https://www.vpforums.org/index.php?app=downloads&showfile=13310
Removed nvram patch. Tested with 10.8.0 and 10.8.1.2021 beta.
=> patch for Titan (Taito do Brasil - 1981) v4

TimonPumbaa/TimonPumbaa.vbs, TimonPumbaa/TimonPumbaa.vbs.original, TimonPumbaa/TimonPumbaa.vbs.patch
https://vpuniverse.com/files/file/8524-timon-and-pumbaas-jungle-pinball/
=> patch: TimonPumbaa

TheATeam_2.0.8/TheATeam.vbs, TheATeam_2.0.8/TheATeam.vbs.original, TheATeam_2.0.8/TheATeam.vbs.patch
https://vpuniverse.com/files/file/17525-the-a-team-original-pinball/
Original script contained mixed line endings 🙄
=> patch: TheATeam_2.0.8

ABBAv2.0/ABBAv2.0.vbs, ABBAv2.0/ABBAv2.0.vbs.patch
https://vpuniverse.com/files/file/5782-abba-v20/
see https://github.com/vpinball/vpinball/issues/1589
same as #280
=> patch: ABBAv2.0 (part 2)

Bounty Hunter (Gottlieb 1985)1.1/Bounty Hunter (Gottlieb 1985).vbs, Bounty Hunter (Gottlieb 1985)1.1/Bounty Hunter (Gottlieb 1985).vbs.original, Bounty Hunter (Gottlieb 1985)1.1/Bounty Hunter (Gottlieb 1985).vbs.patch
https://vpuniverse.com/files/file/6250-bounty-hunter-gottlieb-1985/
Left the 1.0 files as there is a dmd patch in there
=> patch: Bounty Hunter (Gottlieb 1985)1.1

PinballMagic.v1.9.Hybrid.VPX8/PinballMagic.v1.9.Hybrid.VPX8.vbs, PinballMagic.v1.9.Hybrid.VPX8/PinballMagic.v1.9.Hybrid.VPX8.vbs.original, PinballMagic.v1.9.Hybrid.VPX8/PinballMagic.v1.9.Hybrid.VPX8.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=17871
=> patch: PinballMagic.v1.9.Hybrid.VPX8

Blackout (Williams 1980) v1.0.1 - SBR34/Blackout (Williams 1980) v1.0.1 - SBR34.vbs, Blackout (Williams 1980) v1.0.1 - SBR34/Blackout (Williams 1980) v1.0.1 - SBR34.vbs.original, Blackout (Williams 1980) v1.0.1 - SBR34/Blackout (Williams 1980) v1.0.1 - SBR34.vbs.patch
https://vpuniverse.com/files/file/9109-blackout-williams-1980-schlabber34/
* Mixed line endings
* DTArray fixes
=> patch: Blackout (Williams 1980) v1.0.1 - SBR34

Cirqus_Voltaire_Hanibal-Mod_3.7/Cirqus_Voltaire_Hanibal-Mod_3.7.vbs, Cirqus_Voltaire_Hanibal-Mod_3.7/Cirqus_Voltaire_Hanibal-Mod_3.7.vbs.original, Cirqus_Voltaire_Hanibal-Mod_3.7/Cirqus_Voltaire_Hanibal-Mod_3.7.vbs.patch
https://vpuniverse.com/files/file/4176-cirqus-voltaire-1997-hanibals-4k-mod/
This table is a bit a mess if you ask me
closes #290
=> patch: Cirqus_Voltaire_Hanibal-Mod_3.7

Gladiators (Premier 1993) v1.1.1/Gladiators (Premier 1993) v1.1.1.vbs, Gladiators (Premier 1993) v1.1.1/Gladiators (Premier 1993) v1.1.1.vbs.original, Gladiators (Premier 1993) v1.1.1/Gladiators (Premier 1993) v1.1.1.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=13868
Some item is named `Trim` which interferes with the `trim` function.
=> patch: Gladiators (Premier 1993) v1.1.1

Fire Action (Taito do Brasil - 1980) v4/Fire Action (Taito do Brasil - 1980) v4.vbs, Fire Action (Taito do Brasil - 1980) v4/Fire Action (Taito do Brasil - 1980) v4.vbs.original, Fire Action (Taito do Brasil - 1980) v4/Fire Action (Taito do Brasil - 1980) v4.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=13422
replaced getting nvram path from registry by constant relative path "pinmame\nvram"
=> patch: Fire Action (Taito do Brasil - 1980) v4

Space Shuttle (Taito do Brasil - 1982) v4/Space Shuttle (Taito do Brasil - 1982) v4.vbs, Space Shuttle (Taito do Brasil - 1982) v4/Space Shuttle (Taito do Brasil - 1982) v4.vbs.original, Space Shuttle (Taito do Brasil - 1982) v4/Space Shuttle (Taito do Brasil - 1982) v4.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=13644
replaced getting nvram path from registry by constant relative path "pinmame\nvram"
=> patch: Space Shuttle (Taito do Brasil - 1982) v4

Cosmic (Taito do Brasil - 1980) v4/Cosmic (Taito do Brasil - 1980) v4.vbs, Cosmic (Taito do Brasil - 1980) v4/Cosmic (Taito do Brasil - 1980) v4.vbs.original, Cosmic (Taito do Brasil - 1980) v4/Cosmic (Taito do Brasil - 1980) v4.vbs.patch
https://www.vpforums.org/index.php?s=81e3316e17b8e2a79c701d961fdf74f4&app=downloads&showfile=13494
Disabled nvramfix
=> Patch: Cosmic (Taito do Brasil - 1980) v4

Andromeda (Game Plan 1985) v4/Andromeda (Game Plan 1985) v4.vbs, Andromeda (Game Plan 1985) v4/Andromeda (Game Plan 1985) v4.vbs.original, Andromeda (Game Plan 1985) v4/Andromeda (Game Plan 1985) v4.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=14871
Unfortunately we can't set dip switches to have more than one ball, probably can be done on windows and then copying over some pinmame config?
https://github.com/vpinball/vpinball/issues/1210
Similar hex notation issue as #90 
To be seen if we also encounter https://github.com/vpinball/pinmame/issues/262 . I could not reproduce that one.
=> patch: Andromeda (Game Plan 1985) v4

Nine Ball (Stern 1980)/Nine Ball (Stern 1980).vbs, Nine Ball (Stern 1980)/Nine Ball (Stern 1980).vbs.original, Nine Ball (Stern 1980)/Nine Ball (Stern 1980).vbs.patch
https://vpuniverse.com/files/file/8520-nine-ball-stern-1980-sk-3/
=> patch: patch Nine Ball (Stern 1980)

2001 (Gottlieb 1971) v0.99a/2001 (Gottlieb 1971) v0.99a.vbs, 2001 (Gottlieb 1971) v0.99a/2001 (Gottlieb 1971) v0.99a.vbs.original, 2001 (Gottlieb 1971) v0.99a/2001 (Gottlieb 1971) v0.99a.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=17294 
Generic array fix
=> Patch: 2001 (Gottlieb 1971) v0.99a

Munsters (Original 2020) 1.05/Munsters (Original 2020) 1.05.vbs, Munsters (Original 2020) 1.05/Munsters (Original 2020) 1.05.vbs.original, Munsters (Original 2020) 1.05/Munsters (Original 2020) 1.05.vbs.patch
Not sure this table makes a lot of sense as it probably heavily relies on pup packs
Currently crashes vpinball
```
2023-10-04 10:12:20.692 INFO  [78767] [external_create_object@685] progid=PinUpPlayer.PinDisplay, hres=0x00000000
2023-10-04 10:12:20.692 INFO  [78767] [PinUpPlayerPinDisplay::B2SInit@230] Playlists loaded: file=/home/francisdb/vpinball/tables/The Munsters Pro (Stern 2019)/mmunsters/playlists.pup, size=35
2023-10-04 10:12:20.693 INFO  [78767] [PinUpPlayerPinDisplay::B2SInit@251] Triggers loaded: file=/home/francisdb/vpinball/tables/The Munsters Pro (Stern 2019)/mmunsters/triggers.pup, size=3
2023-10-04 10:12:20.693 INFO  [78767] [PinUpPlayerPinDisplay::B2SInit@272] Screens loaded: file=/home/francisdb/vpinball/tables/The Munsters Pro (Stern 2019)/mmunsters/screens.pup, …
```
=> patch: Munsters (Original 2020) 1.05

PinBlob (CLV 2024)/PinBlob (CLV 2024).vbs, PinBlob (CLV 2024)/PinBlob (CLV 2024).vbs.original, PinBlob (CLV 2024)/PinBlob (CLV 2024).vbs.patch
https://vpuniverse.com/files/file/19944-pinblob-original-2024-table-and-pup-pack/
* typical DT/STArray fixes
* rename gamename/rom as there is no alias support
=> patch: PinBlob (CLV 2024)

Darkest Dungeon pupevent_2.2/Darkest Dungeon pupevent_2.2.vbs, Darkest Dungeon pupevent_2.2/Darkest Dungeon pupevent_2.2.vbs.original, Darkest Dungeon pupevent_2.2/Darkest Dungeon pupevent_2.2.vbs.patch
https://vpuniverse.com/files/file/17345-darkest-dungeon-table-pup/
wine issue: https://bugs.winehq.org/show_bug.cgi?id=56781
I do wonder why the `Set` on the dictionary is not working and if removing it does the right thing.
To get the pup pack going I copied `PuP-Pack_Options/3 Screen - FullDMD/*` to the pup pack root
=> patch: Darkest Dungeon pupevent_2.2

MrDoom (Recel 1979)1.3.0/MrDoom (Recel 1979)1.3.0.vbs, MrDoom (Recel 1979)1.3.0/MrDoom (Recel 1979)1.3.0.vbs.original, MrDoom (Recel 1979)1.3.0/MrDoom (Recel 1979)1.3.0.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=15464
Typical DTArray fix
=> patch: MrDoom (Recel 1979)1.3.0

MrEvil (Recel 1979)1.3.0/MrEvil (Recel 1979)1.3.0.vbs, MrEvil (Recel 1979)1.3.0/MrEvil (Recel 1979)1.3.0.vbs.original, MrEvil (Recel 1979)1.3.0/MrEvil (Recel 1979)1.3.0.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=15518
Typical DTArray issue
=> patch: MrEvil (Recel 1979)

pizzatime-65/pizzatime-65.vbs, pizzatime-65/pizzatime-65.vbs.original, pizzatime-65/pizzatime-65.vbs.patch
https://orbitalpin.com/downloads/
Pup pack also works
=> patch: pizzatime-65

Stranger Things - SE 1.47_OSB/Stranger Things - SE 1.47_OSB.vbs, Stranger Things - SE 1.47_OSB/Stranger Things - SE 1.47_OSB.vbs.original, Stranger Things - SE 1.47_OSB/Stranger Things - SE 1.47_OSB.vbs.patch
https://orbitalpin.com/downloads/
If you want the UltraDMD working you need to also get the original edition as it contains the `STLE.UltraDMD` folder (you'll have to rename it)
Mainly a patch to make sure pup pack init happens after the controller init
=> patch: Stranger Things - SE 1.47_OSB

The Beatles_007/The Beatles_007.vbs, The Beatles_007/The Beatles_007.vbs.original, The Beatles_007/The Beatles_007.vbs.patch
https://orbitalpin.com/downloads/
Original script line endings fixed
Fixes for the pup pack initialization sequence
=> patch: The Beatles_007

tlk-0.35/tlk-0.35.vbs, tlk-0.35/tlk-0.35.vbs.original, tlk-0.35/tlk-0.35.vbs.patch
https://orbitalpin.com/downloads/
Fixes for pup pack init
=> patch: tlk-0.35 (The Leprechaun King)

Iron Maiden (Original 2022) VPW 1.0.12/Iron Maiden (Original 2022) VPW 1.0.12.vbs, Iron Maiden (Original 2022) VPW 1.0.12/Iron Maiden (Original 2022) VPW 1.0.12.vbs.original, Iron Maiden (Original 2022) VPW 1.0.12/Iron Maiden (Original 2022) VPW 1.0.12.vbs.patch
https://vpuniverse.com/files/file/12603-iron-maiden-legacy-of-the-beast-original-2022-vpw/?tab=reviews&sort=newest#review-9458
Pup pack still a bit messy but works mostly
=> patch: Iron Maiden (Original 2022) VPW 1.0.12

Metal Slug_1.05/Metal Slug_1.05.vbs, Metal Slug_1.05/Metal Slug_1.05.vbs.original, Metal Slug_1.05/Metal Slug_1.05.vbs.patch
https://vpuniverse.com/files/file/20495-metal-slug/
Typical parenthesis on fist argument issues
This table also sometimes locks up when exiting and the Ultra/FlexDMD sometimes stops working. Maybe related to the fact that it tries to play unsupported wmv files.
=> patch: Metal Slug_1.05

NBA (Stern 2009)_Bigus(MOD)1.4/NBA (Stern 2009)_Bigus(MOD)1.4.vbs, NBA (Stern 2009)_Bigus(MOD)1.4/NBA (Stern 2009)_Bigus(MOD)1.4.vbs.original, NBA (Stern 2009)_Bigus(MOD)1.4/NBA (Stern 2009)_Bigus(MOD)1.4.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=16745
=> patch: NBA (Stern 2009)_Bigus(MOD)1.4

Fifteen (Inder 1974) v4/Fifteen (Inder 1974) v4.vbs, Fifteen (Inder 1974) v4/Fifteen (Inder 1974) v4.vbs.original, Fifteen (Inder 1974) v4/Fifteen (Inder 1974) v4.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=16178#
=> patch: Fifteen (Inder 1974) v4

Harlem Globetrotters (Bally 1979) VPW 1.0/Harlem Globetrotters (Bally 1979) VPW 1.0.vbs, Harlem Globetrotters (Bally 1979) VPW 1.0/Harlem Globetrotters (Bally 1979) VPW 1.0.vbs.original, Harlem Globetrotters (Bally 1979) VPW 1.0/Harlem Globetrotters (Bally 1979) VPW 1.0.vbs.patch
https://vpuniverse.com/files/file/20771-harlem-globetrotters-on-tour-bally-1979-vpw/
Reported on wine issue tracker: https://bugs.winehq.org/show_bug.cgi?id=56931
Reported to the table authors
=> patch: Harlem Globetrotters (Bally 1979) VPW 1.0

Saving Wallden/Saving Wallden.vbs, Saving Wallden/Saving Wallden.vbs.original, Saving Wallden/Saving Wallden.vbs.patch
https://vpuniverse.com/files/file/20304-saving-wallden/
If you start this table in cab mode you will see a big gray square, re-center the table using the tweak menu.
Typical 2-dimensional array access issues.
=> patch: Saving Wallden

MF DOOM (GOILL773 2024) v1.1/MF DOOM (GOILL773 2024) v1.1.vbs, MF DOOM (GOILL773 2024) v1.1/MF DOOM (GOILL773 2024) v1.1.vbs.original, MF DOOM (GOILL773 2024) v1.1/MF DOOM (GOILL773 2024) v1.1.vbs.patch
https://vpuniverse.com/files/file/21045-mf-doom-goill773-2024/
[RegExp issue](https://github.com/vpinball/vpinball/issues/1856) crashes vpinball without any logs
Directory listing not implemented
So switched to manual music listing
=> patch: MF DOOM (GOILL773 2024) v1.1

Sonic The Hedgehog (Brendan Bailey 2005) VPX MOD 1.33/Sonic The Hedgehog (Brendan Bailey 2005) VPX MOD 1.33.vbs, Sonic The Hedgehog (Brendan Bailey 2005) VPX MOD 1.33/Sonic The Hedgehog (Brendan Bailey 2005) VPX MOD 1.33.vbs.original, Sonic The Hedgehog (Brendan Bailey 2005) VPX MOD 1.33/Sonic The Hedgehog (Brendan Bailey 2005) VPX MOD 1.33.vbs.patch
update for the newer version
https://www.vpforums.org/index.php?app=downloads&showfile=17707
=> patch: Sonic The Hedgehog (Brendan Bailey 2005) VPX MOD 1.33

Batman [The Dark Knight] (Stern 2008) 1.16/Batman [The Dark Knight] (Stern 2008) 1.16.vbs, Batman [The Dark Knight] (Stern 2008) 1.16/Batman [The Dark Knight] (Stern 2008) 1.16.vbs.original, Batman [The Dark Knight] (Stern 2008) 1.16/Batman [The Dark Knight] (Stern 2008) 1.16.vbs.patch
https://vpuniverse.com/files/file/11451-batman-the-dark-knight-stern-2008-bord-mod/
Author notified through support section at vpu.
=> patch: Batman [The Dark Knight] (Stern 2008) 1.16

Route66(0_1)/Route66.vbs, Route66(0_1)/Route66.vbs.original, Route66(0_1)/Route66.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=18591
Typical parenthesis issues
=> patch: Route66(0_1)

Dream Daddy1.5/Dream Daddy1.5.vbs, Dream Daddy1.5/Dream Daddy1.5.vbs.original, Dream Daddy1.5/Dream Daddy1.5.vbs.patch
https://vpuniverse.com/files/file/7863-dream-daddy-pinball-the-dad-dating-puppack-adventure/
* Quick fix for the font, used file name and seems to work. 
* Moved pup initialization to table init
* Some pup pack issue reported at 
https://vpuniverse.com/forums/topic/5972-new-vpx-alertdream-daddy-pinball-the-dad-dating-puppack-adventure/#comment-82916
=> patch: Dream Daddy1.5

Route66(0_2)/Route66.vbs, Route66(0_2)/Route66.vbs.original, Route66(0_2)/Route66.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=18591
=> patch: Route66(0_2)

Ramones (HauntFreaks 2021)/Ramones (HauntFreaks 2021).vbs, Ramones (HauntFreaks 2021)/Ramones (HauntFreaks 2021).vbs.orig, Ramones (HauntFreaks 2021)/Ramones (HauntFreaks 2021).vbs.patch
vbs patch for Ramones (HauntFreaks 2021)
=> Added Ramones orig

Legend of Zelda v4.3/Legend of Zelda v4.3.vbs, Legend of Zelda v4.3/Legend of Zelda v4.3.vbs.original, Legend of Zelda v4.3/Legend of Zelda v4.3.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=11608
Reported to table designer:
https://www.vpforums.org/index.php?app=downloads&showfile=11608&st=70#comment_54374
=> patch: Legend of Zelda v4.3

Spooky Wednesday Pro/Spooky Wednesday Pro.vbs, Spooky Wednesday Pro/Spooky Wednesday Pro.vbs.original, Spooky Wednesday Pro/Spooky Wednesday Pro.vbs.patch
https://vpuniverse.com/files/file/18514-spooky-wednesday-vpx-original-2024-table-and-puppack/
This is for the new pro version `Spooky Wednesday Pro.vpx`
Fixes for pup initialization
Pup works mostly, some issues with the UltraDMD, see https://github.com/vpinball/vpinball/issues/1944
=> patch: Spooky Wednesday Pro

Spooky_Wednesday VPX 2024/Spooky_Wednesday VPX 2024.vbs, Spooky_Wednesday VPX 2024/Spooky_Wednesday VPX 2024.vbs.original, Spooky_Wednesday VPX 2024/Spooky_Wednesday VPX 2024.vbs.patch
https://vpuniverse.com/files/file/18514-spooky-wednesday-vpx-original-2024-table-and-puppack/
This is for the normal version `Spooky_Wednesday VPX 2024.vpx`, not the new pro
Fixes for pup initialization
Pup works mostly, some issues with the UltraDMD, see https://github.com/vpinball/vpinball/issues/1944
=> patch: Spooky_Wednesday VPX 2024

Iron Maiden Virtual Time (Original 2020)/Iron Maiden Virtual Time (Original 2020).vbs, Iron Maiden Virtual Time (Original 2020)/Iron Maiden Virtual Time (Original 2020).vbs.original, Iron Maiden Virtual Time (Original 2020)/Iron Maiden Virtual Time (Original 2020).vbs.patch
https://vpuniverse.com/files/file/6257-iron-maiden-virtual-time-imvt/page/3/?tab=comments
Tried to get the music to work but got this:
https://github.com/vpinball/vpinball/issues/1191
wine issue: https://bugs.winehq.org/show_bug.cgi?id=55093
=> patch: Iron Maiden Virtual Time (Original 2020)

Ben-Hur (Staal 1977) V1.1.1 DT-FS-VR-MR Ext2k Conversion/Ben-Hur (Staal 1977) V1.1.1 DT-FS-VR-MR Ext2k Conversion.vbs, Ben-Hur (Staal 1977) V1.1.1 DT-FS-VR-MR Ext2k Conversion/Ben-Hur (Staal 1977) V1.1.1 DT-FS-VR-MR Ext2k Conversion.vbs.original, Ben-Hur (Staal 1977) V1.1.1 DT-FS-VR-MR Ext2k Conversion/Ben-Hur (Staal 1977) V1.1.1 DT-FS-VR-MR Ext2k Conversion.vbs.patch
https://vpuniverse.com/files/file/22519-ben-hur-staal-1977-v11-dt-fs-vr-mr-ext2k-conversion/
=> patch: Ben-Hur (Staal 1977) V1.1.1 DT-FS-VR-MR Ext2k Conversion

You’ll Shoot Your Eye Out! (Shag 2024)/You’ll Shoot Your Eye Out! (Shag 2024).vbs, You’ll Shoot Your Eye Out! (Shag 2024)/You’ll Shoot Your Eye Out! (Shag 2024).vbs.original, You’ll Shoot Your Eye Out! (Shag 2024)/You’ll Shoot Your Eye Out! (Shag 2024).vbs.patch
https://vpuniverse.com/files/file/22694-you%E2%80%99ll-shoot-your-eye-out-shag-2024-b2s/
=> patch: You’ll Shoot Your Eye Out! (Shag 2024)

Ice Age Christmas (Original Balutito 2021) endeemillr mod/Ice Age Christmas (Original Balutito 2021) endeemillr mod.vbs, Ice Age Christmas (Original Balutito 2021) endeemillr mod/Ice Age Christmas (Original Balutito 2021) endeemillr mod.vbs.original, Ice Age Christmas (Original Balutito 2021) endeemillr mod/Ice Age Christmas (Original Balutito 2021) endeemillr mod.vbs.patch
https://vpuniverse.com/files/file/22723-ice-age-christmas-original-balutito-2021-endeemillr-mod/
File system stuff `fso.GetAbsolutePathName(".")`
=> patch: Ice Age Christmas (Original Balutito 2021) endeemillr mod

Bob Marley Mod/Bob Marley Mod.vbs, Bob Marley Mod/Bob Marley Mod.vbs.original, Bob Marley Mod/Bob Marley Mod.vbs.patch
https://vpuniverse.com/files/file/22706-bob-marley-mod/
Disable nvram file modifications
Hard coded music list
=> patch: Bob Marley Mod

Rollercoaster Tycoon (Stern 2002) VPW 2.3/Rollercoaster Tycoon (Stern 2002) VPW 2.3.vbs, Rollercoaster Tycoon (Stern 2002) VPW 2.3/Rollercoaster Tycoon (Stern 2002) VPW 2.3.vbs.original, Rollercoaster Tycoon (Stern 2002) VPW 2.3/Rollercoaster Tycoon (Stern 2002) VPW 2.3.vbs.patch
https://vpuniverse.com/files/file/15973-rollercoaster-tycoon-stern-2002-vpw/
Reported to the vpw team.
=> patch: Rollercoaster Tycoon (Stern 2002) VPW 2.3

Playboy (Bally 1978)/Playboy (Bally 1978).vbs, Playboy (Bally 1978)/Playboy (Bally 1978).vbs.original, Playboy (Bally 1978)/Playboy (Bally 1978).vbs.patch
no sure why that comma is required but fixes this issue:
Saw it being defined like this for other tables
```
2025-01-15 16:47:09.993 ERROR [381963] [CodeViewer::OnScriptError@1213] Script Error at line 3 : Description unavailable
2025-01-15 16:47:09.993 ERROR [381963] [CodeViewer::AppendLastErrorTextW@4032] Runtime error: Line: 3, Character: 42, Description unavailable
2025-01-15 16:47:09.993 ERROR [381963] [CodeViewer::OnScriptError@1213] Script Error at line 2497 : Description unavailable
2025-01-15 16:47:09.993 ERROR [381963] [CodeViewer::AppendLastErrorTextW@4032] Runtime error: Line: 2497, Character: 19, Description unavailable
```
which is an error in the core.vbs
=> patch: Playboy (Bally 1978)

Punchout/Punchout.vbs, Punchout/Punchout.vbs.original, Punchout/Punchout.vbs.patch
https://vpuniverse.com/files/file/23522-punchout/
=> patch: Punchout

Batman66_1.1.0/Batman66_1.1.0.vbs, Batman66_1.1.0/Batman66_1.1.0.vbs.patch
=> Batman66_1.1.0 part 2

Scarface-Original-2025-1.0.2/Scarface-Original-2025-1.0.2.vbs, Scarface-Original-2025-1.0.2/Scarface-Original-2025-1.0.2.vbs.original, Scarface-Original-2025-1.0.2/Scarface-Original-2025-1.0.2.vbs.patch
https://vpuniverse.com/files/file/24133-scarface/
Tries to read a file in the pup pack folder
=> patch: Scarface-Original-2025-1.0.2

Simpsons (Data East 1990)_Bigus(MOD)3.1/Simpsons (Data East 1990)_Bigus(MOD)3.1.vbs, Simpsons (Data East 1990)_Bigus(MOD)3.1/Simpsons (Data East 1990)_Bigus(MOD)3.1.vbs.original, Simpsons (Data East 1990)_Bigus(MOD)3.1/Simpsons (Data East 1990)_Bigus(MOD)3.1.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=14333
The FlexDMD code behaves differently than on windows. (`Empty`)
=> patch: Simpsons (Data East 1990)_Bigus(MOD)3.1

Freddys Nightmares/Freddys Nightmares.vbs, Freddys Nightmares/Freddys Nightmares.vbs.original, Freddys Nightmares/Freddys Nightmares.vbs.patch
https://vpuniverse.com/files/file/23895-freddys-nightmares-original-table-and-pup-pack/
- Mostly moving stuff around to get proper pup pack init
- Some wmv issues
- Probably some other pup pack issues
=> patch: Freddys Nightmares

AC-DC LUCI Premium VR (Stern 2013) v1.1.3/AC-DC LUCI Premium VR (Stern 2013) v1.1.3.vbs, AC-DC LUCI Premium VR (Stern 2013) v1.1.3/AC-DC LUCI Premium VR (Stern 2013) v1.1.3.vbs.original, AC-DC LUCI Premium VR (Stern 2013) v1.1.3/AC-DC LUCI Premium VR (Stern 2013) v1.1.3.vbs.patch
TL:DR; Table now works in master with correct lighting.
The details: this patch gets the latest version of this table working in master. I did the following
- diffed the earlier v.1.1 table.vbs.original with the patched v1.1 table [at this link](https://github.com/vpinball/vpinball/issues/1939#issuecomment-2480881832) and manually applied any changes related to treating `CageBall.ID` and `CollBall.ID` being writeable to the newer v1.1.3 version of the table (i.e. reverted back to the `userValue` property). That patched v1.1 version still works but [has horrible light bloom](https://github.com/jsm174/vpx-standalone-scripts/pull/354#issuecomment-2663507090) in master
- applied the v1.1.3 fixes from [@nicals](https://github.com/Nicals) [earlier …
=> AC-DC LUCI Premium VR (Stern 2013) v1.1.3 patch - Works with current master

Iron Maiden (Original 2022) VPW 1.0.12/Iron Maiden (Original 2022) VPW 1.0.12.vbs
closes #363 
Something is probably wrong with the lookup logic of that table.
=> patch: Iron Maiden (Original 2022) VPW 1.0.12 (rainbow fix)

FNAF/FNAF.vbs, FNAF/FNAF.vbs.original, FNAF/FNAF.vbs.patch
Five nights at freddy's (FNAF)
https://vpuniverse.com/files/file/8397-five-nights-at-freddyfnaf
* typical sub parenthesis issue
fixes #378
=> patch: FNAF

Ducktales (Orginal 2020)/DUCKTALES.vbs, Ducktales (Orginal 2020)/DUCKTALES.vbs.patch
https://vpuniverse.com/files/file/8402-ducktales/ v1.6 update
* typical sub parenthesis issue
I do however have issues launching balls on this version because the plunger is misaligned.
=> patch: DUCKTALES 1.6

Monkey Island VR Room/Monkey Island VR Room.vbs, Monkey Island VR Room/Monkey Island VR Room.vbs.original, Monkey Island VR Room/Monkey Island VR Room.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=16157
* typical `.ID` -> `.UserValue`
* typical sub call with parenthesis issue
fixes #375
=> patch: Monkey Island VR Room

Monkeyislandv1.1/monkeyisland.vbs.original.vbs, Monkeyislandv1.1/monkeyisland.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=16157
Updated patch for the typical `.ID` -> `.UserValue`
for the VR Room version see #377 
requested in #375
=> patch: Monkeyislandv1.1

indochinecentral/indochinecentral.vbs, indochinecentral/indochinecentral.vbs.original, indochinecentral/indochinecentral.vbs.patch, indochinecentralPUP/indochinecentralPUP.vbs, indochinecentralPUP/indochinecentralPUP.vbs.original, indochinecentralPUP/indochinecentralPUP.vbs.patch
https://vpuniverse.com/files/file/13484-indochine-central-tour/
closes #371
=> patch: indochinecentral

Wednesday (Netflix 2023)/Wednesday (Netflix 2023).vbs, Wednesday (Netflix 2023)/Wednesday (Netflix 2023).vbs.original, Wednesday (Netflix 2023)/Wednesday (Netflix 2023).vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=17872
- Make sure you have the music in `music/Wed`. Seems this is still case sensitive.
- Since this removes the taito nvram switching code you have to make sure games are fully done when you close the table or next time it will start up with the previous game still going.
=> patch: Wednesday (Netflix 2023)

Alfred Hitchcock's Psycho (TBA 2019)/Alfred Hitchcock's Psycho (TBA 2019).vbs, Alfred Hitchcock's Psycho (TBA 2019)/Alfred Hitchcock's Psycho (TBA 2019).vbs.original, Alfred Hitchcock's Psycho (TBA 2019)/Alfred Hitchcock's Psycho (TBA 2019).vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=14323
I do wonder how these callbacks work on windows with the `..`
Table could also use an info update as it's currently labeled as `Vortex` in the table info.
=> patch: Alfred Hitchcock's Psycho (TBA 2019)

TX-Sector (Gottlieb 1988) SG1bsoN Mod V1.1/TX-Sector (Gottlieb 1988) SG1bsoN Mod V1.1.vbs, TX-Sector (Gottlieb 1988) SG1bsoN Mod V1.1/TX-Sector (Gottlieb 1988) SG1bsoN Mod V1.1.vbs.original, TX-Sector (Gottlieb 1988) SG1bsoN Mod V1.1/TX-Sector (Gottlieb 1988) SG1bsoN Mod V1.1.vbs.patch
https://vpuniverse.com/files/file/9459-tx-sector-gottlieb-1988-sg1bson-mod/
* typical `DTArray` fix
* commented some debug leftovers
=> patch: TX-Sector (Gottlieb 1988) SG1bsoN Mod V1.1.vbs

Oba Oba (Taito do Brasil - 1979) v55_VPX8/Oba Oba (Taito do Brasil - 1979) v55_VPX8.vbs, Oba Oba (Taito do Brasil - 1979) v55_VPX8/Oba Oba (Taito do Brasil - 1979) v55_VPX8.vbs.original, Oba Oba (Taito do Brasil - 1979) v55_VPX8/Oba Oba (Taito do Brasil - 1979) v55_VPX8.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=13344
* Typical rom nvram reset code (`NVramPatchLoad`) that we disable
Table will not work properly if you don't finish games
=> patch: Oba Oba (Taito do Brasil - 1979) v55_VPX8

Stellar Wars (Williams 1979)/Stellar Wars (Williams 1979).vbs, Stellar Wars (Williams 1979)/Stellar Wars (Williams 1979).vbs.original, Stellar Wars (Williams 1979)/Stellar Wars (Williams 1979).vbs.patch
https://vpuniverse.com/files/file/9376-stellar-wars-williams-1979/
* typical DTArray fixes
=> patch: Stellar Wars (Williams 1979)

Meteor (Stern 1979)/Meteor (Stern 1979).vbs, Meteor (Stern 1979)/Meteor (Stern 1979).vbs.original, Meteor (Stern 1979)/Meteor (Stern 1979).vbs.patch
https://vpuniverse.com/files/file/8519-meteor-stern-1979-sk-5/
* typical `DTArray` fix applied using [vpxtool](https://github.com/francisdb/vpxtool)
=> patch: Meteor (Stern 1979)

HALO/HALO.vbs, HALO/HALO.vbs.original, HALO/HALO.vbs.patch
https://vpuniverse.com/files/file/8399-halo/
fixes #385
=> patch: HALO

Attack On Titan (cHuG_MOD_1.4)/Attack On Titan (cHuG_MOD_1.4).vbs, Attack On Titan (cHuG_MOD_1.4)/Attack On Titan (cHuG_MOD_1.4).vbs.original, Attack On Titan (cHuG_MOD_1.4)/Attack On Titan (cHuG_MOD_1.4).vbs.patch
https://vpuniverse.com/files/file/10567-attack-on-titan-mod/
=> patch: Attack On Titan (cHuG_MOD_1.4)

DORAEMON/DORAEMON.vbs, DORAEMON/DORAEMON.vbs.original, DORAEMON/DORAEMON.vbs.patch
https://vpuniverse.com/files/file/8401-doraemon/
fixes #384
=> patch: DORAEMON

SMGP (Super Mario Galaxy Pinball)/SMGP.vbs, SMGP (Super Mario Galaxy Pinball)/SMGP.vbs.original, SMGP (Super Mario Galaxy Pinball)/SMGP.vbs.patch
https://vpuniverse.com/files/file/8403-super-mario-galaxy-pinball/
* typical parenthesis fix
fixes #383
=> patch: SMGP (Super Mario Galaxy Pinball)

Streets of Rage (TBA 2018)/Streets of Rage (TBA 2018).vbs, Streets of Rage (TBA 2018)/Streets of Rage (TBA 2018).vbs.original, Streets of Rage (TBA 2018)/Streets of Rage (TBA 2018).vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=13659
* typical first argument starting with parenthesis issues
Issues:
* affected by https://github.com/vpinball/vpinball/issues/2318
* table does not exit properly but hangs
* overblown lights similar to https://github.com/vpinball/vpinball/issues/662 and https://github.com/vpinball/vpinball/issues/792 but that's something the table author should fix?
=> patch: Streets of Rage (TBA 2018)

Gremlins by Balutito 1.7/Gremlins by Balutito 1.7.vbs, Gremlins by Balutito 1.7/Gremlins by Balutito 1.7.vbs.original, Gremlins by Balutito 1.7/Gremlins by Balutito 1.7.vbs.patch
* const used before being declared
* disabled custom `cvpmDips` setup `Creating an object of type "VPinMAME.WSHDlg" is not supported`
closes #387
=> patch: Gremlins by Balutito 1.7

1679379865_jurassicparklimitededition/1679379865_jurassicparklimitededition.vbs, 1679379865_jurassicparklimitededition/1679379865_jurassicparklimitededition.vbs.original, 1679379865_jurassicparklimitededition/1679379865_jurassicparklimitededition.vbs.patch
https://vpuniverse.com/files/file/8659-jurassic-parc-limited-edition/
* typical pup pack init ordering issues
* requires https://github.com/vpinball/vpinball/pull/2352
_The pup pack is a mess: lots of missing folders, unrelated playlists copied from other tables, missing images_
=> patch: 1679379865_jurassicparklimitededition

TheATeam_3.0.2/TheATeam.vbs, TheATeam_3.0.2/TheATeam.vbs.original, TheATeam_3.0.2/TheATeam.vbs.patch
https://vpuniverse.com/files/file/17525-the-a-team-original-table/
* Typical parenthesis issue
Reported to the author at https://vpuniverse.com/forums/topic/9613-new-vp10-alert-the-a-team-original-table/page/2/#findComment-86977
=> patch: TheATeam 3.0.2

Sons Of Anarchy (Original 2019)/Sons Of Anarchy (Original 2019).vbs, Sons Of Anarchy (Original 2019)/Sons Of Anarchy (Original 2019).vbs.original, Sons Of Anarchy (Original 2019)/Sons Of Anarchy (Original 2019).vbs.patch
https://vpuniverse.com/files/file/6131-sons-of-anarchy-original-2019-vpx/
* UltraDMD GetDMDColor disabled
* typical parenthesis issues
Casing issues on UltraDMD to be fixed by renaming files
see https://github.com/vpinball/vpinball/issues/1944 , will be fixed by https://github.com/vpinball/vpinball/pull/2347
=> patch: Sons Of Anarchy (Original 2019)

Running Horse (Inder 1976) v55_VPX8/Running Horse (Inder 1976) v55_VPX8.vbs, Running Horse (Inder 1976) v55_VPX8/Running Horse (Inder 1976) v55_VPX8.vbs.original, Running Horse (Inder 1976) v55_VPX8/Running Horse (Inder 1976) v55_VPX8.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=16751
* same as #397
=> patch: Running Horse (Inder 1976) v55_VPX8

Black & Red (Inder 1975) v4.3/Black & Red (Inder 1975) v4.3.vbs.patch, Black & Red (Inder 1975) v55_VPX8/Black & Red (Inder 1975) v55_VPX8.vbs, Black & Red (Inder 1975) v55_VPX8/Black & Red (Inder 1975) v55_VPX8.vbs.original, Black & Red (Inder 1975) v55_VPX8/Black & Red (Inder 1975) v55_VPX8.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=16238#
* same as #397
=> patch: Black & Red (Inder 1975) v55_VPX8

Big Horse (Maresa 1975) v55_VPX8/Big Horse (Maresa 1975) v55_VPX8.vbs, Big Horse (Maresa 1975) v55_VPX8/Big Horse (Maresa 1975) v55_VPX8.vbs.original, Big Horse (Maresa 1975) v55_VPX8/Big Horse (Maresa 1975) v55_VPX8.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=14227#
=> patch: Big Horse (Maresa 1975) v55_VPX8

Luck Smile (Inder 1976) 1p v55_VPX8/Luck Smile (Inder 1976) 1p v55_VPX8.vbs, Luck Smile (Inder 1976) 1p v55_VPX8/Luck Smile (Inder 1976) 1p v55_VPX8.vbs.original, Luck Smile (Inder 1976) 1p v55_VPX8/Luck Smile (Inder 1976) 1p v55_VPX8.vbs.patch, Luck Smile (Inder 1976) 4p v55_VPX8/Luck Smile (Inder 1976) 4p v55_VPX8.vbs, Luck Smile (Inder 1976) 4p v55_VPX8/Luck Smile (Inder 1976) 4p v55_VPX8.vbs.original, Luck Smile (Inder 1976) 4p v55_VPX8/Luck Smile (Inder 1976) 4p v55_VPX8.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=16285
=> patch: Luck Smile (Inder 1976) 1p/4p v55_VPX8

Honey (Williams 1971)V1.2/Honey (Williams 1971)V1.2.vbs.patch, Honey (Williams 1971)V1.3/Honey (Williams 1971)V1.3.vbs, Honey (Williams 1971)V1.3/Honey (Williams 1971)V1.3.vbs.original, Honey (Williams 1971)V1.3/Honey (Williams 1971)V1.3.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=16915
Updates previous patch for new 1.3 version
=> patch: Honey (Williams 1971)V1.3

Vampirella1 .3/Vampirella1 .3.vbs, Vampirella1 .3/Vampirella1 .3.vbs.original, Vampirella1 .3/Vampirella1 .3.vbs.patch
https://vpuniverse.com/files/file/21669-vampirella-balutito-mod/
* same patch as the table it is based on #47
=> patch: Vampirella1 .3

Aztec High-Tapped (Williams 1976)/Aztec High-Tapped (Williams 1976).vbs, Aztec High-Tapped (Williams 1976)/Aztec High-Tapped (Williams 1976).vbs.original, Aztec High-Tapped (Williams 1976)/Aztec High-Tapped (Williams 1976).vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=18245
* mixed line endings (makes this an ugly patch)
* `Const tnob` used before being declared
=> patch: Aztec High-Tapped (Williams 1976)

Stranger Things 4 Premium/Stranger Things 4 Premium.vbs, Stranger Things 4 Premium/Stranger Things 4 Premium.vbs.original, Stranger Things 4 Premium/Stranger Things 4 Premium.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=16930
* `CreateObject("PinUpPlayer.PinDisplay")`  was done twice
* Fixed pup init order by moving everythign out of the script top level into `InitPUP`
In general not a fan of this bloated table, see https://www.vpforums.org/index.php?app=core&module=global&section=comments&parentId=16930&fromApp=downloads-files&do=findComment&comment_id=54268
Remaining issues:
* `StrangerThings4_Premium.UltraDMD/scoreboard-background.png` missing
* `avantgarde` font not found, maybe it should fall back to `ITC Avant Garde Gothic LT Bold.ttf` (`avantgarde lt medium`)? see also https://github.com/vpinball/vpinball/pull/2114 and https://github.com/vpinball/vpinball/pull/2117
* duplicate playlist and screen definitions, defined both in the script and …
=> patch: Stranger Things 4 Premium

The Rolling Stones (Stern 2011)_Bigus(MOD)3.0/The Rolling Stones (Stern 2011)_Bigus(MOD)3.0.vbs, The Rolling Stones (Stern 2011)_Bigus(MOD)3.0/The Rolling Stones (Stern 2011)_Bigus(MOD)3.0.vbs.original, The Rolling Stones (Stern 2011)_Bigus(MOD)3.0/The Rolling Stones (Stern 2011)_Bigus(MOD)3.0.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=15508
* `.id` -> `.Uservalue`
=> patch: The Rolling Stones (Stern 2011)_Bigus(MOD)3.0

Three Angels (Original 2018) LW/Three Angels (Original 2018) LW.vbs, Three Angels (Original 2018) LW/Three Angels (Original 2018) LW.vbs.original, Three Angels (Original 2018) LW/Three Angels (Original 2018) LW.vbs.patch
https://vpuniverse.com/files/file/24248-three-angels-4k/
* something was messed up with the previous patch
* https://vpuniverse.com/forums/topic/11576-new-vp10-alert-three-angels-4k/#findComment-86111
=> patch: Three Angels (Original 2018) LW 2.0.3

Motley Crue SS/Motley Crue SS.vbs, Motley Crue SS/Motley Crue SS.vbs.original, Motley Crue SS/Motley Crue SS.vbs.patch
https://vpuniverse.com/files/file/23896-motley-crue-ss-no-pup/
* typical parenthesis issue (error on line 0)
* typical UltraDMD color registry lookup issue
=> patch: Motley Crue SS

BeastieBoysv1.0/BeastieBoysv1.0.vbs, BeastieBoysv1.0/BeastieBoysv1.0.vbs.original, BeastieBoysv1.0/BeastieBoysv1.0.vbs.patch
https://vpuniverse.com/files/file/25400-beastie-boys/
* typical DT/STArray issues fixed with vpxtool
=> patch: BeastieBoysv1.0

Wipe Out (Premier 1993) 1.1.0/Wipe Out (Premier 1993) 1.1.0.vbs, Wipe Out (Premier 1993) 1.1.0/Wipe Out (Premier 1993) 1.1.0.vbs.original, Wipe Out (Premier 1993) 1.1.0/Wipe Out (Premier 1993) 1.1.0.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=14171
* conflict between a primitive named Trim and the vbscript function `Trim`
So the Trim primitive will stay in it's default visibility.
=> patch: Wipe Out (Premier 1993) 1.1.0

Van Halen 1.2/Van Halen 1.2.vbs, Van Halen 1.2/Van Halen 1.2.vbs.original, Van Halen 1.2/Van Halen 1.2.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=15167
*This table has a heavy b2s that causes input delays / stuttering. Good for b2s perf testing.*
=> patch: Van Halen 1.2

Jungle_Queen/Jungle_Queen.vbs, Jungle_Queen/Jungle_Queen.vbs.original, Jungle_Queen/Jungle_Queen.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=15576
* Table was using old `b2s.vbs`, adjusted to use modern b2s calls.
*This was mainly some guesswork, guess somebody should properly port this to 10.8.x*
=> patch: Jungle_Queen

Stranger Things (Original 2020) LW/Stranger Things (Original 2020) LW.vbs, Stranger Things (Original 2020) LW/Stranger Things (Original 2020) LW.vbs.original, Stranger Things (Original 2020) LW/Stranger Things (Original 2020) LW.vbs.patch
https://vpuniverse.com/files/file/25396-stranger-things-20/
* same patch as the table this is based on (pup init) #305
=> patch: Stranger Things (Original 2020) LW

Roller Coaster (Gottlieb 1971)x/Roller Coaster (Gottlieb 1971)x.vbs, Roller Coaster (Gottlieb 1971)x/Roller Coaster (Gottlieb 1971)x.vbs.original, Roller Coaster (Gottlieb 1971)x/Roller Coaster (Gottlieb 1971)x.vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=17770
* `Me(...)` used in `Spinner_Hit`  yields `Script Error at line 1` https://bugs.winehq.org/show_bug.cgi?id=58248
=> patch: Roller Coaster (Gottlieb 1971)x

A-Go-Go (Williams 1966)/A-Go-Go (Williams 1966).vbs, A-Go-Go (Williams 1966)/A-Go-Go (Williams 1966).vbs.original, A-Go-Go (Williams 1966)/A-Go-Go (Williams 1966).vbs.patch
https://www.vpforums.org/index.php?app=downloads&showfile=19060
* Boolean setting read as number failing
* Also requires https://github.com/vpinball/vpinball/pull/2441 -> https://github.com/vpinball/vpinball/pull/2443
I think boolean settings are stored as `0`/`1` on windows where standalone stores them as `True`/`False` and because of that `CDbl` does not fail on windows. Not sure how to read the windows `VPREg.stg` file.
=> patch: A-Go-Go (Williams 1966)
